/**
 * Le Chat Parisien — Language & Phrase Data
 * All static content data for the language learning app.
 */

// ═══════════ Supported Languages ═══════════
const LANGS = {
    french: { name: 'French', flag: '🇫🇷', native: 'Français', hi: 'Bonjour!' },
    korean: { name: 'Korean', flag: '🇰🇷', native: '한국어', hi: '안녕하세요!' },
};

// ═══════════ Fluency Levels ═══════════
const LEVELS = {
    beginner:     { name: 'Complete Beginner',  emoji: '🌱', desc: 'I know almost nothing yet' },
    elementary:   { name: 'Elementary',         emoji: '🌿', desc: 'I know basic words & greetings' },
    intermediate: { name: 'Intermediate',       emoji: '🌳', desc: 'I can hold simple conversations' },
    upper:        { name: 'Upper Intermediate', emoji: '🌲', desc: 'I can discuss many topics' },
    advanced:     { name: 'Advanced',           emoji: '🏔️', desc: 'I want to perfect my skills' },
};

// ═══════════ Quick Demo Phrases (legacy fallback) ═══════════
const DEMO = {
    french: [
        { p: "Mon chat prépare le petit-déjeuner.", m: "My cat is preparing breakfast.", kw: ["breakfast", "cook"] },
        { p: "Le chat va au travail en métro.", m: "The cat goes to work by subway.", kw: ["subway", "work"] },
        { p: "Mon chat étudie pour son examen.", m: "My cat is studying for his exam.", kw: ["study", "exam"] },
        { p: "Le chat fait les courses au supermarché.", m: "The cat goes grocery shopping at the supermarket.", kw: ["shop", "grocery"] },
        { p: "Mon chat a un rendez-vous chez le médecin.", m: "My cat has a doctor's appointment.", kw: ["doctor", "appointment"] },
        { p: "Le chat appelle ses parents tous les dimanches.", m: "The cat calls his parents every Sunday.", kw: ["call", "family"] },
        { p: "Mon chat cherche un nouvel appartement.", m: "My cat is looking for a new apartment.", kw: ["apartment", "search"] },
        { p: "Le chat prend un café avec ses collègues.", m: "The cat has coffee with his colleagues.", kw: ["coffee", "colleagues"] },
        { p: "Mon chat fait du sport le week-end.", m: "My cat exercises on weekends.", kw: ["sport", "weekend"] },
        { p: "Le chat regarde un film après le dîner.", m: "The cat watches a movie after dinner.", kw: ["movie", "dinner"] },
    ],
    korean: [
        { p: "고양이가 아침을 준비해요.", m: "The cat is preparing breakfast.", kw: ["breakfast", "cook"] },
        { p: "고양이가 지하철로 출근해요.", m: "The cat commutes to work by subway.", kw: ["subway", "work"] },
        { p: "고양이가 시험 공부를 해요.", m: "The cat is studying for an exam.", kw: ["study", "exam"] },
        { p: "고양이가 마트에서 장을 봐요.", m: "The cat goes grocery shopping at the mart.", kw: ["shop", "grocery"] },
        { p: "고양이가 병원 예약이 있어요.", m: "The cat has a hospital appointment.", kw: ["hospital", "appointment"] },
        { p: "고양이는 매주 일요일에 부모님께 전화해요.", m: "The cat calls his parents every Sunday.", kw: ["call", "family"] },
        { p: "고양이가 새 아파트를 찾고 있어요.", m: "The cat is looking for a new apartment.", kw: ["apartment", "search"] },
        { p: "고양이가 동료들과 커피를 마셔요.", m: "The cat has coffee with colleagues.", kw: ["coffee", "colleagues"] },
        { p: "고양이는 주말에 운동해요.", m: "The cat exercises on weekends.", kw: ["sport", "weekend"] },
        { p: "고양이가 저녁 식사 후에 영화를 봐요.", m: "The cat watches a movie after dinner.", kw: ["movie", "dinner"] },
    ],
};

// ═══════════ Level-Specific Phrase Banks ═══════════
const LEVEL_DEMO = {
    french: {
        beginner: [
            // A1 — Present tense, basic vocabulary, simple structures
            { p: "Mon chat est calme.", m: "My cat is calm.", kw: ["calme", "adjective"] },
            { p: "Je mange du fromage.", m: "I eat cheese.", kw: ["fromage", "food"] },
            { p: "Mon chat est paresseux.", m: "My cat is lazy.", kw: ["paresseux", "adjective"] },
            { p: "Je joue avec mes amis.", m: "I play with my friends.", kw: ["jouer", "amis"] },
            { p: "Mon chat est jeune et beau.", m: "My cat is young and handsome.", kw: ["jeune", "beau"] },
            { p: "J'aime la glace.", m: "I like ice cream.", kw: ["glace", "food"] },
            { p: "Elle est très sociable.", m: "She is very sociable.", kw: ["sociable", "adjective"] },
            { p: "Il court dans la rue.", m: "He runs in the street.", kw: ["courir", "rue"] },
            { p: "Mon chat nage dans l'eau.", m: "My cat swims in the water.", kw: ["nager", "eau"] },
            { p: "Je dors dans la chambre.", m: "I sleep in the bedroom.", kw: ["chambre", "dormir"] },
            { p: "Je travaille à la maison.", m: "I work from home.", kw: ["travailler", "maison"] },
            { p: "Il ouvre la porte.", m: "He opens the door.", kw: ["ouvrir", "porte"] },
            { p: "J'écoute de la musique.", m: "I listen to music.", kw: ["écouter", "musique"] },
            { p: "Je cherche mes amis.", m: "I'm looking for my friends.", kw: ["chercher", "amis"] },
            { p: "Mon chat est affectueux.", m: "My cat is affectionate.", kw: ["affectueux", "adjective"] },
            { p: "Les enfants grimpent sur les meubles.", m: "The kids climb on the furniture.", kw: ["grimper", "meubles"] },
            { p: "Il est un peu têtu.", m: "He is a bit stubborn.", kw: ["têtu", "adjective"] },
            { p: "J'aide mes voisins.", m: "I help my neighbors.", kw: ["aider", "voisins"] },
            { p: "J'achète un cadeau pour ma mère.", m: "I buy a gift for my mother.", kw: ["acheter", "cadeau"] },
            { p: "Je ferme la porte.", m: "I close the door.", kw: ["fermer", "porte"] },
            { p: "Je lis un livre.", m: "I read a book.", kw: ["lire", "livre"] },
            { p: "Elle écrit dans son carnet.", m: "She writes in her notebook.", kw: ["écrire", "carnet"] },
            { p: "Mon chat est aventureux.", m: "My cat is adventurous.", kw: ["aventureux", "adjective"] },
            { p: "Je prépare le dîner.", m: "I prepare dinner.", kw: ["préparer", "dîner"] },
            { p: "Il est poli avec les gens.", m: "He is polite with people.", kw: ["poli", "gens"] },
            { p: "Elle peint un beau tableau.", m: "She paints a beautiful painting.", kw: ["peindre", "beau"] },
            { p: "Je mange un plat délicieux.", m: "I eat a delicious dish.", kw: ["plat", "délicieux"] },
            { p: "Je salue mes collègues.", m: "I greet my colleagues.", kw: ["saluer", "collègues"] },
            { p: "Je suis libre le week-end.", m: "I'm free on the weekend.", kw: ["libre", "week-end"] },
            { p: "Il fait chaud, je bois de l'eau.", m: "It's hot, I drink water.", kw: ["chaud", "eau"] },
            // A1 — Conversational phrases
            { p: "De rien.", m: "You're welcome.", kw: ["polite", "welcome"] },
            { p: "Je vous en prie.", m: "You're welcome. (formal)", kw: ["formal", "polite"] },
            { p: "J'aime ça.", m: "I like that.", kw: ["aimer", "like"] },
            { p: "Ça dépend.", m: "It depends.", kw: ["depends", "maybe"] },
            { p: "Pas encore.", m: "Not yet.", kw: ["pas", "encore"] },
            { p: "Pas vraiment.", m: "Not really.", kw: ["pas", "vraiment"] },
            { p: "Bof, ça va.", m: "Meh, it's okay.", kw: ["bof", "okay"] },
            { p: "Il fait chaud.", m: "It's hot.", kw: ["chaud", "weather"] },
            { p: "Il fait froid.", m: "It's cold.", kw: ["froid", "weather"] },
            { p: "Il pleut.", m: "It's raining.", kw: ["pluie", "weather"] },
            { p: "Quelle heure est-il ?", m: "What time is it?", kw: ["heure", "time"] },
            { p: "Je dîne.", m: "I'm having dinner.", kw: ["dîner", "food"] },
            { p: "Je fais de la musculation.", m: "I do weight training.", kw: ["muscu", "sport"] },
            { p: "Je me lave le visage.", m: "I wash my face.", kw: ["visage", "routine"] },
            { p: "Tu viens d'où ?", m: "Where are you from?", kw: ["venir", "question"] },
            { p: "Je suis fatigué.", m: "I'm tired.", kw: ["fatigué", "feeling"] },
            { p: "C'est super !", m: "That's great!", kw: ["super", "expression"] },
            { p: "Où est la gare ?", m: "Where is the train station?", kw: ["gare", "direction"] },
            { p: "Je ne sais pas.", m: "I don't know.", kw: ["savoir", "negation"] },
            { p: "C'est combien ?", m: "How much is it?", kw: ["combien", "shopping"] },
            { p: "Tu as des frères et sœurs ?", m: "Do you have brothers and sisters?", kw: ["famille", "question"] },
            { p: "Je suis marié.", m: "I'm married.", kw: ["marié", "status"] },
            { p: "On se retrouve à quelle heure ?", m: "What time do we meet?", kw: ["heure", "question"] },
            { p: "Je voudrais un café, s'il vous plaît.", m: "I'd like a coffee, please.", kw: ["café", "polite"] },
            { p: "Qu'est-ce que tu fais dans la vie ?", m: "What do you do for a living?", kw: ["travail", "question"] },
            { p: "J'habite à Paris.", m: "I live in Paris.", kw: ["habiter", "city"] },
            { p: "C'est loin d'ici ?", m: "Is it far from here?", kw: ["loin", "direction"] },
            { p: "Je suis en retard.", m: "I'm late.", kw: ["retard", "time"] },
            { p: "Enchanté !", m: "Nice to meet you!", kw: ["greeting", "polite"] },
            { p: "Tu parles anglais ?", m: "Do you speak English?", kw: ["parler", "question"] },
        ],
        elementary: [
            // A2 — Passé composé, reflexive verbs, negation, questions
            { p: "Je me lève tôt le matin.", m: "I get up early in the morning.", kw: ["se lever", "tôt"] },
            { p: "Il se brosse les dents après le petit-déjeuner.", m: "He brushes his teeth after breakfast.", kw: ["se brosser", "dents"] },
            { p: "Je me douche le soir.", m: "I shower in the evening.", kw: ["se doucher", "soir"] },
            { p: "Elle s'occupe de ses enfants.", m: "She takes care of her children.", kw: ["s'occuper de", "enfants"] },
            { p: "Mon chat se couche tard.", m: "My cat goes to bed late.", kw: ["se coucher", "tard"] },
            { p: "J'ai trouvé un nouveau restaurant.", m: "I found a new restaurant.", kw: ["trouver", "restaurant"] },
            { p: "Mon chat a acheté des meubles pour sa chambre.", m: "My cat bought furniture for his bedroom.", kw: ["acheter", "meubles"] },
            { p: "J'ai rencontré mes collègues au cinéma.", m: "I met my colleagues at the cinema.", kw: ["rencontrer", "cinéma"] },
            { p: "Elle a cuisiné un plat délicieux.", m: "She cooked a delicious dish.", kw: ["cuisiner", "délicieux"] },
            { p: "On a découvert un beau magasin.", m: "We discovered a beautiful shop.", kw: ["découvrir", "magasin"] },
            { p: "Mon chat ne sort jamais sans sa laisse.", m: "My cat never goes out without his leash.", kw: ["ne...jamais", "laisse"] },
            { p: "Je n'ai rien mangé ce matin.", m: "I ate nothing this morning.", kw: ["ne...rien", "manger"] },
            { p: "Il ne veut plus dormir seul.", m: "He doesn't want to sleep alone anymore.", kw: ["ne...plus", "seul"] },
            { p: "Personne ne comprend mon chat.", m: "Nobody understands my cat.", kw: ["ne...personne", "comprendre"] },
            { p: "Je n'ai connu personne à la fête.", m: "I didn't know anyone at the party.", kw: ["personne", "passé composé"] },
            { p: "Je fais de la musculation le matin.", m: "I do weight training in the morning.", kw: ["musculation", "faire de"] },
            { p: "Il joue du piano tous les soirs.", m: "He plays piano every evening.", kw: ["jouer de", "piano"] },
            { p: "Je fais les courses à l'épicerie.", m: "I go grocery shopping at the grocery store.", kw: ["courses", "épicerie"] },
            { p: "J'ai reçu un cadeau de mes voisins.", m: "I received a gift from my neighbors.", kw: ["recevoir", "cadeau"] },
            { p: "Je sors avec mes amis deux fois par semaine.", m: "I go out with my friends twice a week.", kw: ["deux fois", "amis"] },
            { p: "Tu as l'air fatigué.", m: "You look tired.", kw: ["avoir l'air", "fatigué"] },
            { p: "Mon chat vient de manger.", m: "My cat just ate.", kw: ["venir de", "manger"] },
            { p: "Tout s'est bien passé au travail.", m: "Everything went well at work.", kw: ["tout", "bien passé"] },
            { p: "J'ai hâte de commencer ma formation.", m: "I'm looking forward to starting my training.", kw: ["avoir hâte", "formation"] },
            { p: "Je me suis présenté à mes nouveaux voisins.", m: "I introduced myself to my new neighbors.", kw: ["se présenter", "voisins"] },
            { p: "On a déménagé à la campagne.", m: "We moved to the countryside.", kw: ["déménager", "campagne"] },
            { p: "J'ai salué les invités.", m: "I greeted the guests.", kw: ["saluer", "invités"] },
            { p: "Elle s'entraîne pour une compétition de danse.", m: "She trains for a dance competition.", kw: ["s'entraîner", "danse"] },
            { p: "Mon chat a vendu sa vieille maison.", m: "My cat sold his old house.", kw: ["vendre", "vieux"] },
            { p: "J'ai commencé le bénévolat.", m: "I started volunteering.", kw: ["commencer", "bénévolat"] },
            { p: "Il a arrêté de fumer.", m: "He stopped smoking.", kw: ["arrêter", "fumer"] },
            { p: "Je continue de m'entraîner petit à petit.", m: "I continue to train little by little.", kw: ["continuer", "petit à petit"] },
            { p: "Je me suis fait beaucoup d'amis grâce à mon voisin.", m: "I made a lot of friends thanks to my neighbor.", kw: ["se faire des amis", "grâce à"] },
            { p: "Je ne me souviens pas du mot.", m: "I don't remember the word.", kw: ["se souvenir", "mot"] },
            { p: "J'ai montré ma chambre à mes amis.", m: "I showed my bedroom to my friends.", kw: ["montrer", "chambre"] },
            // A2 — Conversational phrases
            { p: "Tu as fait quoi hier ?", m: "What did you do yesterday?", kw: ["hier", "question"] },
            { p: "Tout s'est bien passé.", m: "Everything went well.", kw: ["bien", "passé"] },
            { p: "J'ai hâte !", m: "I'm looking forward to it!", kw: ["hâte", "excited"] },
            { p: "Je viens de manger.", m: "I just ate.", kw: ["venir de", "just"] },
            { p: "Il a l'air très jeune.", m: "He looks very young.", kw: ["avoir l'air", "look"] },
            { p: "Je ne me souviens pas.", m: "I don't remember.", kw: ["souvenir", "remember"] },
            { p: "Je me lève 5 minutes avant le travail.", m: "I wake up 5 minutes before work.", kw: ["se lever", "work"] },
            { p: "Je ne me lève pas tôt.", m: "I don't get up early.", kw: ["negation", "routine"] },
            { p: "Je me douche le soir.", m: "I shower at night.", kw: ["se doucher", "routine"] },
            { p: "J'écris dans un journal.", m: "I write in a diary.", kw: ["écrire", "journal"] },
            { p: "Je sors mon chat avec une laisse tous les jours.", m: "I walk my cat with a leash every day.", kw: ["laisse", "chat"] },
            { p: "Je me fais beaucoup d'amis grâce à mon chat.", m: "I make a lot of friends thanks to my cat.", kw: ["amis", "grâce à"] },
            { p: "Je donne à manger aux chats.", m: "I feed the cats.", kw: ["manger", "chat"] },
            { p: "Je brosse les poils de mon chat.", m: "I brush my cat's fur.", kw: ["poils", "chat"] },
            { p: "Tu es allée au cinéma ?", m: "Did you go to the cinema?", kw: ["cinéma", "question"] },
            { p: "Vous êtes prête ?", m: "Are you ready? (formal)", kw: ["prête", "ready"] },
            { p: "Ça vous a plu ?", m: "Did you enjoy it?", kw: ["plaire", "enjoy"] },
            { p: "Que recommandez-vous ?", m: "What do you recommend?", kw: ["recommend", "question"] },
            { p: "Combien coûte le bus ?", m: "How much does the bus cost?", kw: ["prix", "bus"] },
            { p: "À quelle heure est le prochain bus ?", m: "What time is the next bus?", kw: ["heure", "bus"] },
            { p: "Je travaille dans une entreprise technologique.", m: "I work in a tech company.", kw: ["entreprise", "work"] },
            { p: "Je ne passe pas de temps avec mes collègues.", m: "I don't spend time with my colleagues.", kw: ["collègues", "negation"] },
            { p: "Alors je me sens seule.", m: "So I feel lonely.", kw: ["seule", "feeling"] },
            { p: "Je dois partir 5 minutes plus tôt.", m: "I have to leave 5 minutes earlier.", kw: ["devoir", "tôt"] },
        ],
        intermediate: [
            // B1 — Imparfait + passé composé, depuis/il y a, COD/COI/EN/Y, comparisons, relative pronouns
            { p: "Quand j'étais jeune, je grimpais partout sur les meubles.", m: "When I was young, I used to climb everywhere on the furniture.", kw: ["imparfait", "grimper"] },
            { p: "Je marchais dans la rue quand j'ai rencontré un ami.", m: "I was walking on the street when I met a friend.", kw: ["imparfait+PC", "rencontrer"] },
            { p: "Je faisais de la musculation quand il a commencé à pleuvoir.", m: "I was doing weight training when it started raining.", kw: ["imparfait+PC", "pleuvoir"] },
            { p: "Il était paresseux, mais il a décidé de changer.", m: "He was lazy, but he decided to change.", kw: ["imparfait+PC", "décider"] },
            { p: "Je me sentais seul, alors je me suis fait des amis.", m: "I felt lonely, so I made friends.", kw: ["se sentir", "se faire des amis"] },
            { p: "Mon chat habitait en Corée quand il était jeune.", m: "My cat used to live in Korea when he was young.", kw: ["imparfait", "habiter"] },
            { p: "Je jouais du piano quand quelqu'un a frappé à la porte.", m: "I was playing piano when someone knocked on the door.", kw: ["imparfait+PC", "piano"] },
            { p: "Il réfléchissait à son avenir quand il a reçu une offre.", m: "He was thinking about his future when he received an offer.", kw: ["réfléchir", "imparfait+PC"] },
            { p: "Il faisait froid, alors je suis resté à la maison.", m: "It was cold, so I stayed home.", kw: ["imparfait+PC", "froid"] },
            { p: "Les enfants se comportaient bien devant les invités.", m: "The children were behaving well in front of the guests.", kw: ["se comporter", "imparfait"] },
            { p: "J'habite dans cette maison depuis trois ans.", m: "I've been living in this house for three years.", kw: ["depuis", "habiter"] },
            { p: "J'étudie le français depuis l'année dernière.", m: "I've been studying French since last year.", kw: ["depuis", "étudier"] },
            { p: "J'attends le bus depuis vingt minutes.", m: "I've been waiting for the bus for twenty minutes.", kw: ["depuis", "attendre"] },
            { p: "Il y a cinq ans, on a déménagé à la campagne.", m: "Five years ago, we moved to the countryside.", kw: ["il y a", "déménager"] },
            { p: "J'ai travaillé pendant douze ans dans une entreprise.", m: "I worked for twelve years in a company.", kw: ["pendant", "travailler"] },
            { p: "Ce film ? Je l'ai regardé deux fois.", m: "This movie? I watched it twice. (COD: l')", kw: ["COD", "deux fois"] },
            { p: "Des livres, j'en ai beaucoup.", m: "Books — I have a lot of them. (EN replaces des livres)", kw: ["EN", "livres"] },
            { p: "Je vais au cinéma — j'y vais avec mes amis.", m: "I go to the cinema — I go there with my friends. (Y replaces au cinéma)", kw: ["Y", "cinéma"] },
            { p: "J'ai envoyé un cadeau à ma voisine — je lui ai envoyé des fleurs.", m: "I sent a gift to my neighbor — I sent her flowers. (COI: lui)", kw: ["COI", "cadeau"] },
            { p: "Je pense à mon travail — j'y pense souvent.", m: "I think about my work — I think about it often. (Y replaces à + thing)", kw: ["Y", "penser à"] },
            { p: "Je mange de la glace tous les jours — j'en mange beaucoup.", m: "I eat ice cream every day — I eat a lot of it. (EN replaces de la glace)", kw: ["EN", "glace"] },
            { p: "Mon frère est plus aventureux que ses voisins.", m: "My brother is more adventurous than his neighbors.", kw: ["plus que", "comparatif"] },
            { p: "Ma femme est la meilleure cuisinière de la famille.", m: "My wife is the best cook in the family.", kw: ["meilleur", "superlatif"] },
            { p: "J'ai huit ans de plus que mon frère.", m: "I'm eight years older than my brother.", kw: ["de plus que", "comparatif"] },
            { p: "Le restaurant où je travaillais est fermé.", m: "The restaurant where I used to work is closed. (où = where)", kw: ["où", "pronom relatif"] },
            { p: "Le livre que je lis est sur le développement personnel.", m: "The book I'm reading is about personal development. (que = that)", kw: ["que", "pronom relatif"] },
            { p: "J'ai un ami qui est cascadeur.", m: "I have a friend who is a stunt performer. (qui = who)", kw: ["qui", "pronom relatif"] },
            { p: "Le quartier dont je parle est dangereux.", m: "The neighborhood I'm talking about is dangerous. (dont = about which)", kw: ["dont", "pronom relatif"] },
            { p: "J'ai réparé l'ordinateur de mon voisin.", m: "I fixed my neighbor's computer.", kw: ["réparer", "ordinateur"] },
            { p: "Je tapais sur l'ordinateur quand l'écran est devenu bleu.", m: "I was typing on the computer when the screen turned blue.", kw: ["imparfait+PC", "ordinateur"] },
            { p: "J'économise pour acheter de nouveaux meubles.", m: "I'm saving to buy new furniture.", kw: ["économiser", "meubles"] },
            { p: "J'évite les endroits dangereux la nuit.", m: "I avoid dangerous places at night.", kw: ["éviter", "dangereux"] },
            { p: "Je dois partir cinq minutes plus tôt pour le travail.", m: "I have to leave five minutes earlier for work.", kw: ["devoir", "plus tôt"] },
            { p: "Je me soucie de la nature et de l'environnement.", m: "I care about nature and the environment.", kw: ["se soucier de", "nature"] },
            { p: "J'ai discuté avec mes collègues pendant la pause.", m: "I chatted with my colleagues during the break.", kw: ["discuter", "collègues"] },
            { p: "J'ai décrit mon métier à mes amis.", m: "I described my job to my friends.", kw: ["décrire", "métier"] },
            { p: "Je tolère mon voisin désagréable.", m: "I tolerate my unpleasant neighbor.", kw: ["tolérer", "désagréable"] },
            { p: "On a créé une application pour trouver des amis.", m: "We created an app to find friends.", kw: ["créer", "trouver"] },
            { p: "Je viens de Corée — j'en viens et j'y retourne chaque été.", m: "I come from Korea — I come from there and return there every summer. (EN + Y)", kw: ["EN", "Y"] },
            { p: "Tu ne te lèves pas tôt ? — Si, je me lève tôt le lundi !", m: "You don't get up early? — Actually yes, I do on Monday! (si vs non)", kw: ["si", "negation"] },
            // B1 — Subjunctive
            { p: "Il faut que tu viennes à la réunion demain.", m: "You need to come to the meeting tomorrow.", kw: ["subjonctif", "réunion"] },
            { p: "Je veux que tu sois heureux.", m: "I want you to be happy.", kw: ["subjonctif", "heureux"] },
            { p: "Il est important que nous arrivions à l'heure.", m: "It's important that we arrive on time.", kw: ["subjonctif", "heure"] },
            { p: "Bien qu'il pleuve, je sors quand même.", m: "Although it's raining, I'm going out anyway.", kw: ["subjonctif", "pleuvoir"] },
            { p: "Il faut que je fasse les courses ce soir.", m: "I need to go grocery shopping tonight.", kw: ["subjonctif", "courses"] },
            { p: "Je doute qu'il vienne à la fête.", m: "I doubt he'll come to the party.", kw: ["subjonctif", "fête"] },
            { p: "Il faut que vous soyez patients.", m: "You need to be patient.", kw: ["subjonctif", "patience"] },
            { p: "Avant que tu partes, dis-moi la vérité.", m: "Before you leave, tell me the truth.", kw: ["subjonctif", "vérité"] },
            { p: "Il est nécessaire que tu apprennes le français.", m: "It's necessary that you learn French.", kw: ["subjonctif", "français"] },
            { p: "Je suis content que tu sois là.", m: "I'm glad you're here.", kw: ["subjonctif", "content"] },
            // B1 — Futur simple
            { p: "Demain, je travaillerai à la maison.", m: "Tomorrow, I will work from home.", kw: ["futur simple", "demain"] },
            { p: "L'année prochaine, nous voyagerons en France.", m: "Next year, we will travel to France.", kw: ["futur simple", "voyage"] },
            { p: "Elle finira ses études en juin.", m: "She will finish her studies in June.", kw: ["futur simple", "études"] },
            { p: "Quand je serai grand, je serai médecin.", m: "When I grow up, I will be a doctor.", kw: ["futur simple", "médecin"] },
            { p: "Tu verras, tout ira bien.", m: "You'll see, everything will be fine.", kw: ["futur simple", "bien"] },
            { p: "Nous nous marierons l'année prochaine.", m: "We will get married next year.", kw: ["futur simple", "mariage"] },
            { p: "Il pleuvra demain selon la météo.", m: "It will rain tomorrow according to the forecast.", kw: ["futur simple", "météo"] },
            { p: "Je t'appellerai dès que j'arriverai.", m: "I'll call you as soon as I arrive.", kw: ["futur simple", "appeler"] },
            { p: "Ils achèteront une nouvelle maison.", m: "They will buy a new house.", kw: ["futur simple", "maison"] },
            { p: "Qu'est-ce que tu feras après tes études ?", m: "What will you do after your studies?", kw: ["futur simple", "études"] },
            // B1 — Conditional
            { p: "Si j'avais plus de temps, je voyagerais davantage.", m: "If I had more time, I would travel more.", kw: ["conditionnel", "voyage"] },
            { p: "Si j'étais riche, j'achèterais une grande maison.", m: "If I were rich, I would buy a big house.", kw: ["conditionnel", "riche"] },
            { p: "Pourriez-vous m'aider, s'il vous plaît ?", m: "Could you help me, please?", kw: ["conditionnel", "aider"] },
            { p: "Je voudrais réserver une table pour deux.", m: "I would like to reserve a table for two.", kw: ["conditionnel", "réserver"] },
            { p: "Si tu avais le choix, où habiterais-tu ?", m: "If you had the choice, where would you live?", kw: ["conditionnel", "choix"] },
            { p: "À ta place, je ne dirais rien.", m: "In your place, I wouldn't say anything.", kw: ["conditionnel", "place"] },
            { p: "Si nous partions plus tôt, nous éviterions le trafic.", m: "If we left earlier, we would avoid the traffic.", kw: ["conditionnel", "trafic"] },
            { p: "Aimeriez-vous venir avec nous ?", m: "Would you like to come with us?", kw: ["conditionnel", "venir"] },
            { p: "Sans ton aide, je ne réussirais pas.", m: "Without your help, I wouldn't succeed.", kw: ["conditionnel", "aide"] },
            { p: "Que ferais-tu à ma place ?", m: "What would you do in my place?", kw: ["conditionnel", "place"] },
            // B1 — Imperative
            { p: "Viens ici tout de suite !", m: "Come here right now!", kw: ["impératif", "viens"] },
            { p: "Ferme la porte, s'il te plaît.", m: "Close the door, please.", kw: ["impératif", "porte"] },
            { p: "Ne sois pas en retard.", m: "Don't be late.", kw: ["impératif", "retard"] },
            { p: "Asseyez-vous, je vous prie.", m: "Please sit down. (formal)", kw: ["impératif", "asseyez"] },
            { p: "Faisons une pause.", m: "Let's take a break.", kw: ["impératif", "pause"] },
            { p: "Ne t'inquiète pas, tout va bien.", m: "Don't worry, everything's fine.", kw: ["impératif", "inquiète"] },
            { p: "Parlez plus lentement, s'il vous plaît.", m: "Please speak more slowly. (formal)", kw: ["impératif", "lentement"] },
            { p: "Allons-y !", m: "Let's go!", kw: ["impératif", "allons"] },
            { p: "Écoute-moi bien.", m: "Listen to me carefully.", kw: ["impératif", "écoute"] },
            { p: "N'oublie pas ton parapluie.", m: "Don't forget your umbrella.", kw: ["impératif", "parapluie"] },
            // B1 — Conversational phrases
            { p: "Quand j'étais enfant, je jouais du piano.", m: "When I was a child, I played the piano.", kw: ["imparfait", "piano"] },
            { p: "J'habitais en Corée.", m: "I used to live in Korea.", kw: ["imparfait", "habiter"] },
            { p: "Il faisait beau, alors j'ai fait du sport.", m: "The weather was nice, so I exercised.", kw: ["imparfait+PC", "sport"] },
            { p: "J'habite ici depuis douze ans.", m: "I've been living here for twelve years.", kw: ["depuis", "habiter"] },
            { p: "J'ai travaillé pendant 12 ans.", m: "I worked for 12 years.", kw: ["pendant", "travailler"] },
            { p: "Comment tu as découvert ce livre ?", m: "How did you discover this book?", kw: ["découvrir", "question"] },
            { p: "Tu penses que tu vas continuer de te réveiller tôt ?", m: "Do you think you'll keep waking up early?", kw: ["penser", "futur"] },
            { p: "Quelle est la chose qui est la plus importante pour toi ?", m: "What is the most important thing for you?", kw: ["important", "question"] },
            { p: "Si je dois choisir...", m: "If I have to choose...", kw: ["si", "choisir"] },
            { p: "Mon ordinateur est tombé en panne.", m: "My computer broke down.", kw: ["ordinateur", "panne"] },
            { p: "Je tapais quand soudain l'ordinateur a affiché un écran bleu.", m: "I was typing when suddenly the computer showed a blue screen.", kw: ["imparfait+PC", "ordinateur"] },
            { p: "Il faut que je répare ça vite.", m: "I need to fix this quickly.", kw: ["il faut", "réparer"] },
            { p: "Quand est-ce que je peux récupérer mon ordinateur ?", m: "When can I get my computer back?", kw: ["récupérer", "question"] },
            { p: "Pouvez-vous m'aider ?", m: "Can you help me? (formal)", kw: ["aider", "formal"] },
            { p: "J'ai beaucoup d'expérience professionnelle.", m: "I have a lot of work experience.", kw: ["expérience", "work"] },
            { p: "Vous pouvez vous présenter ?", m: "Can you introduce yourself? (formal)", kw: ["se présenter", "formal"] },
            { p: "Petit à petit.", m: "Little by little.", kw: ["petit", "progress"] },
            { p: "Tu peux répéter ?", m: "Can you repeat?", kw: ["répéter", "question"] },
            { p: "Je ne comprends pas ces mots, vous pouvez reformuler ?", m: "I don't understand these words, can you rephrase?", kw: ["comprendre", "reformuler"] },
            { p: "Vous vous offrez des cadeaux ?", m: "Do you give each other gifts?", kw: ["cadeau", "question"] },
            { p: "Tu préfères les mêmes ou différents restaurants ?", m: "Do you prefer the same or different restaurants?", kw: ["préférer", "restaurant"] },
            { p: "Comment est la semaine ? Tu fais quoi ?", m: "How's the week? What are you doing?", kw: ["semaine", "question"] },
            { p: "Tu utilises beaucoup l'IA ?", m: "Do you use AI a lot?", kw: ["AI", "question"] },
            { p: "Je suis intéressée par votre entreprise.", m: "I'm interested in your company.", kw: ["intéressé", "entreprise"] },
            { p: "J'aime les valeurs de votre entreprise.", m: "I like your company's values.", kw: ["valeurs", "entreprise"] },
            // Wedding conversation
            { p: "Beaucoup de mariages font une entrée comme ça ?", m: "Do a lot of weddings have an entrance like that?", kw: ["mariage", "question"] },
            { p: "Le marié était derrière l'écran.", m: "The groom was behind the screen.", kw: ["marié", "wedding"] },
            { p: "Combien de temps dure la cérémonie ?", m: "How long does the ceremony last?", kw: ["combien", "durée"] },
            { p: "Il y a un repas après la cérémonie ?", m: "Is there a meal after the ceremony?", kw: ["repas", "question"] },
            { p: "Habituellement, on fait un dîner après.", m: "Usually, we have a dinner afterwards.", kw: ["habituellement", "dîner"] },
            { p: "Ils portaient des vêtements traditionnels.", m: "They were wearing traditional clothes.", kw: ["vêtements", "traditionnels"] },
            { p: "J'aime l'idée d'aller dans un club après le mariage.", m: "I like the idea of going to a club after the wedding.", kw: ["idée", "mariage"] },
            { p: "Où est-ce que vous êtes allés pour la lune de miel ?", m: "Where did you go for the honeymoon?", kw: ["lune de miel", "wedding"] },
            { p: "Vous passez combien de temps en lune de miel ?", m: "How much time do you spend on your honeymoon?", kw: ["combien", "temps"] },
            { p: "La mariée était très jolie.", m: "The bride was very pretty.", kw: ["jolie", "wedding"] },
            // Family & people
            { p: "Ma belle-mère est venue nous voir.", m: "My mother-in-law came to visit us.", kw: ["belle-mère", "family"] },
            { p: "Ma grand-mère maternelle habite loin.", m: "My maternal grandmother lives far away.", kw: ["grand-mère", "family"] },
            { p: "Ils sont venus nous voir le week-end dernier.", m: "They came to see us last weekend.", kw: ["venir", "passé composé"] },
            { p: "Ma femme et moi, on aime voyager.", m: "My wife and I like to travel.", kw: ["femme", "family"] },
            { p: "Je ne pensais pas que c'était possible.", m: "I didn't think it was possible.", kw: ["penser", "imparfait"] },
            { p: "Elles ont une grande maison.", m: "They have a big house.", kw: ["avoir", "grande"] },
            { p: "Tu connais cette chanson ?", m: "Do you know this song?", kw: ["connaître", "question"] },
            // Travel & time
            { p: "Il y a très longtemps, j'habitais en France.", m: "A very long time ago, I lived in France.", kw: ["il y a", "temps"] },
            { p: "Vous êtes restés plus longtemps que prévu ?", m: "Did you stay longer than expected?", kw: ["rester", "passé composé"] },
            { p: "C'est devenu très populaire.", m: "It became very popular.", kw: ["devenir", "passé composé"] },
            { p: "Les photos sont floues, tu peux en reprendre ?", m: "The photos are blurry, can you retake them?", kw: ["floues", "photos"] },
            { p: "On voyait les étoiles depuis le balcon.", m: "We could see the stars from the balcony.", kw: ["étoiles", "imparfait"] },
            { p: "Je fais du tapis roulant tous les matins.", m: "I do the treadmill every morning.", kw: ["tapis roulant", "sport"] },
            // Animals & café conversation
            { p: "Vous pouvez toucher les animaux dans les cafés ?", m: "Can you touch the animals in the cafés?", kw: ["toucher", "question"] },
            { p: "Les hamsters ne sont pas sauvages ?", m: "Hamsters aren't wild?", kw: ["sauvage", "question"] },
            { p: "Non, ils ne sont pas domestiques.", m: "No, they're not domestic.", kw: ["domestique", "animal"] },
            { p: "Mon chat me manquait quand j'étais en voyage.", m: "I missed my cat when I was traveling.", kw: ["manquer", "imparfait"] },
            // Everyday expressions
            { p: "C'est pareil pour moi.", m: "It's the same for me.", kw: ["pareil", "expression"] },
            { p: "Il y a eu un éclair dans le ciel.", m: "There was a lightning bolt in the sky.", kw: ["éclair", "weather"] },
            { p: "Elle prie tous les soirs.", m: "She prays every evening.", kw: ["prier", "verb"] },
            { p: "Ma fille collectionne les poupées et les figurines.", m: "My daughter collects dolls and figurines.", kw: ["poupée", "figurine"] },
            // B1 — Plus-que-parfait
            { p: "J'avais déjà mangé quand il est arrivé.", m: "I had already eaten when he arrived.", kw: ["plus-que-parfait", "manger"] },
            { p: "Elle avait fini ses devoirs avant de sortir.", m: "She had finished her homework before going out.", kw: ["plus-que-parfait", "finir"] },
            { p: "Nous avions réservé une table, mais le restaurant était fermé.", m: "We had reserved a table, but the restaurant was closed.", kw: ["plus-que-parfait", "réserver"] },
            { p: "Il avait oublié son parapluie, alors il est revenu.", m: "He had forgotten his umbrella, so he came back.", kw: ["plus-que-parfait", "oublier"] },
            { p: "J'avais toujours voulu visiter le Japon.", m: "I had always wanted to visit Japan.", kw: ["plus-que-parfait", "vouloir"] },
            { p: "Ils avaient déménagé avant la fin de l'année.", m: "They had moved before the end of the year.", kw: ["plus-que-parfait", "déménager"] },
            { p: "Tu n'avais jamais goûté ce plat avant ?", m: "You had never tasted this dish before?", kw: ["plus-que-parfait", "goûter"] },
            { p: "On s'était déjà rencontrés à une fête.", m: "We had already met at a party.", kw: ["plus-que-parfait", "se rencontrer"] },
            // B1 — Passive voice
            { p: "Ce livre a été écrit par un auteur français.", m: "This book was written by a French author.", kw: ["passif", "écrire"] },
            { p: "La maison a été construite en 1920.", m: "The house was built in 1920.", kw: ["passif", "construire"] },
            { p: "Les résultats seront annoncés demain.", m: "The results will be announced tomorrow.", kw: ["passif", "annoncer"] },
            { p: "Le voleur a été arrêté par la police.", m: "The thief was arrested by the police.", kw: ["passif", "arrêter"] },
            { p: "Cette chanson est chantée partout dans le monde.", m: "This song is sung all over the world.", kw: ["passif", "chanter"] },
            { p: "Le dîner est préparé par ma grand-mère.", m: "Dinner is prepared by my grandmother.", kw: ["passif", "préparer"] },
            // B1 — Reported speech
            { p: "Il m'a dit qu'il viendrait demain.", m: "He told me he would come tomorrow.", kw: ["discours indirect", "dire"] },
            { p: "Elle a demandé si j'avais fini.", m: "She asked if I had finished.", kw: ["discours indirect", "demander"] },
            { p: "Mon patron m'a expliqué que le projet était urgent.", m: "My boss explained to me that the project was urgent.", kw: ["discours indirect", "expliquer"] },
            { p: "Il a répondu qu'il ne savait pas.", m: "He replied that he didn't know.", kw: ["discours indirect", "répondre"] },
            { p: "Elle m'a demandé ce que je voulais manger.", m: "She asked me what I wanted to eat.", kw: ["discours indirect", "ce que"] },
            { p: "Ils ont annoncé que le vol était retardé.", m: "They announced that the flight was delayed.", kw: ["discours indirect", "annoncer"] },
            // B1 — Opinions & argumentation connectors
            { p: "À mon avis, ce film est excellent.", m: "In my opinion, this movie is excellent.", kw: ["opinion", "à mon avis"] },
            { p: "Je pense que tu as raison.", m: "I think you're right.", kw: ["opinion", "penser"] },
            { p: "Je crois que c'est une bonne idée.", m: "I believe it's a good idea.", kw: ["opinion", "croire"] },
            { p: "Je suis d'accord avec toi.", m: "I agree with you.", kw: ["opinion", "d'accord"] },
            { p: "Je ne suis pas du tout d'accord.", m: "I don't agree at all.", kw: ["opinion", "désaccord"] },
            { p: "D'un côté c'est pratique, de l'autre c'est cher.", m: "On one hand it's practical, on the other it's expensive.", kw: ["argumentation", "d'un côté"] },
            { p: "Il pleut, donc je reste à la maison.", m: "It's raining, so I'm staying home.", kw: ["connecteur", "donc"] },
            { p: "Puisque tu es là, on peut commencer.", m: "Since you're here, we can start.", kw: ["connecteur", "puisque"] },
            { p: "Il est fatigué, pourtant il continue de travailler.", m: "He's tired, yet he keeps working.", kw: ["connecteur", "pourtant"] },
            { p: "J'aime le café, en revanche je déteste le thé.", m: "I like coffee; on the other hand, I hate tea.", kw: ["connecteur", "en revanche"] },
            { p: "C'est un bon restaurant, cependant les prix sont élevés.", m: "It's a good restaurant; however, the prices are high.", kw: ["connecteur", "cependant"] },
            { p: "J'adore voyager, car ça me permet de découvrir de nouvelles cultures.", m: "I love traveling because it lets me discover new cultures.", kw: ["connecteur", "car"] },
            { p: "D'abord, je fais mes devoirs, ensuite je regarde la télé, enfin je me couche.", m: "First I do my homework, then I watch TV, finally I go to bed.", kw: ["connecteur", "séquence"] },
            { p: "En ce qui me concerne, je préfère le train à l'avion.", m: "As far as I'm concerned, I prefer the train to the plane.", kw: ["opinion", "en ce qui me concerne"] },
            // B1 — More subjunctive triggers
            { p: "Je parle lentement pour que tu comprennes.", m: "I speak slowly so that you understand.", kw: ["subjonctif", "pour que"] },
            { p: "Finis tes devoirs avant qu'il soit trop tard.", m: "Finish your homework before it's too late.", kw: ["subjonctif", "avant que"] },
            { p: "On sort à moins qu'il pleuve.", m: "We'll go out unless it rains.", kw: ["subjonctif", "à moins que"] },
            { p: "J'attendrai jusqu'à ce que tu sois prêt.", m: "I'll wait until you're ready.", kw: ["subjonctif", "jusqu'à ce que"] },
            { p: "Je doute qu'il vienne ce soir.", m: "I doubt he'll come tonight.", kw: ["subjonctif", "douter que"] },
            { p: "Il est possible qu'on parte plus tôt.", m: "It's possible we leave earlier.", kw: ["subjonctif", "il est possible que"] },
            { p: "Je suis content que tu aies réussi ton examen.", m: "I'm glad you passed your exam.", kw: ["subjonctif", "content que"] },
            { p: "Il faut que nous fassions attention.", m: "We need to be careful.", kw: ["subjonctif", "il faut que"] },
            // B1 — Formal register
            { p: "Madame, Monsieur, je vous écris au sujet de ma candidature.", m: "Dear Sir/Madam, I'm writing regarding my application.", kw: ["formel", "candidature"] },
            { p: "Veuillez trouver ci-joint mon CV.", m: "Please find attached my CV.", kw: ["formel", "ci-joint"] },
            { p: "Je vous remercie par avance de votre réponse.", m: "Thank you in advance for your reply.", kw: ["formel", "remercier"] },
            { p: "Dans l'attente de votre réponse, je vous prie d'agréer mes salutations distinguées.", m: "Awaiting your reply, yours sincerely.", kw: ["formel", "salutations"] },
            { p: "Suite à notre conversation téléphonique, je vous confirme ma disponibilité.", m: "Following our phone call, I confirm my availability.", kw: ["formel", "confirmer"] },
            { p: "Je me permets de vous contacter au sujet de l'annonce.", m: "I'm taking the liberty of contacting you regarding the ad.", kw: ["formel", "se permettre"] },
            { p: "Pourriez-vous me donner plus de renseignements ?", m: "Could you give me more information?", kw: ["formel", "renseignements"] },
            { p: "Je souhaiterais prendre rendez-vous.", m: "I would like to make an appointment.", kw: ["formel", "rendez-vous"] },
            // B1 — Everyday expressions
            { p: "C'est n'importe quoi !", m: "That's nonsense!", kw: ["expression", "n'importe quoi"] },
            { p: "J'en ai marre de ce bruit.", m: "I'm fed up with this noise.", kw: ["expression", "en avoir marre"] },
            { p: "T'inquiète, c'est pas grave.", m: "Don't worry, it's no big deal.", kw: ["expression", "t'inquiète"] },
            { p: "Ça me fait plaisir de te voir.", m: "It makes me happy to see you.", kw: ["expression", "faire plaisir"] },
            { p: "On verra bien.", m: "We'll see.", kw: ["expression", "on verra"] },
            { p: "Ça vaut le coup d'essayer.", m: "It's worth trying.", kw: ["expression", "valoir le coup"] },
            { p: "Je n'en reviens pas !", m: "I can't believe it!", kw: ["expression", "revenir"] },
            { p: "Ça m'énerve.", m: "That annoys me.", kw: ["expression", "énerver"] },
            { p: "On se tient au courant.", m: "Let's keep each other posted.", kw: ["expression", "au courant"] },
            { p: "J'ai la flemme.", m: "I can't be bothered / I'm feeling lazy.", kw: ["expression", "flemme"] },
            { p: "C'est pas mon truc.", m: "It's not my thing.", kw: ["expression", "truc"] },
            { p: "Il faut que j'y aille.", m: "I have to go.", kw: ["expression", "y aller"] },
            { p: "Ça me dit rien.", m: "I don't feel like it. / Doesn't ring a bell.", kw: ["expression", "ça me dit"] },
            { p: "Tu me manques.", m: "I miss you.", kw: ["expression", "manquer"] },
            { p: "C'est la galère.", m: "It's a nightmare / hassle.", kw: ["expression", "galère"] },
            { p: "Bonne continuation !", m: "All the best! (going forward)", kw: ["expression", "continuation"] },
            { p: "Ça roule !", m: "Sounds good! / All good!", kw: ["expression", "ça roule"] },
            { p: "Je suis débordé en ce moment.", m: "I'm swamped right now.", kw: ["expression", "débordé"] },
        ],
    },
    korean: {
        beginner: [
            { p: "고양이가 요리해요.", m: "My cat cooks.", kw: ["cook", "kitchen"] },
            { p: "고양이가 공부해요.", m: "The cat studies.", kw: ["study", "learn"] },
            { p: "고양이가 일해요.", m: "The cat works.", kw: ["work", "job"] },
            { p: "고양이가 먹어요.", m: "The cat eats.", kw: ["eat", "food"] },
        ],
        elementary: [
            { p: "내 고양이는 학교에 가요.", m: "My cat goes to school.", kw: ["school", "go"] },
            { p: "고양이가 버스를 타요.", m: "The cat takes the bus.", kw: ["bus", "ride"] },
            { p: "내 고양이는 장을 봐요.", m: "My cat goes grocery shopping.", kw: ["shop", "grocery"] },
            { p: "고양이가 저녁을 준비해요.", m: "The cat prepares dinner.", kw: ["dinner", "cook"] },
        ],
        intermediate: [
            { p: "내 고양이는 올해 고등학교를 졸업해요.", m: "My cat is graduating from high school this year.", kw: ["graduate", "school"] },
            { p: "고양이가 내일 면접이 있어요.", m: "The cat has a job interview tomorrow.", kw: ["interview", "job"] },
            { p: "내 고양이가 가족을 위해 특별한 저녁을 요리했어요.", m: "My cat cooked a special dinner for the family.", kw: ["cook", "family"] },
            { p: "고양이는 매일 아침 지하철을 타고 출근해요.", m: "The cat takes the subway to work every morning.", kw: ["subway", "work"] },
        ],
        upper: [
            { p: "내 고양이는 학위를 받기까지 5년 동안 공부했어요.", m: "My cat studied for five years before getting his degree.", kw: ["degree", "study"] },
            { p: "첫 번째 면접에서 떨어졌지만 내 고양이는 포기하지 않았어요.", m: "Although he failed his first interview, my cat didn't give up.", kw: ["interview", "persist"] },
            { p: "내 고양이는 커리어를 위해 해외 이주를 고려하고 있어요.", m: "My cat is considering moving abroad for his career.", kw: ["abroad", "career"] },
            { p: "고양이는 일이 너무 많아서 휴가를 취소해야 했어요.", m: "The cat had to cancel his vacation because he had too much work.", kw: ["vacation", "cancel"] },
        ],
        advanced: [
            { p: "꾸준히 노력한 끝에 내 고양이는 꿈의 직장을 얻었어요.", m: "Through steady effort, my cat landed his dream job.", kw: ["dream", "career"] },
            { p: "내 고양이는 일과 공부를 병행하느라 눈코 뜰 새 없이 바빠요.", m: "My cat is incredibly busy juggling work and studies. (Idiom: 눈코 뜰 새 없다)", kw: ["busy", "burnout"] },
            { p: "오랫동안 고민한 끝에 내 고양이는 창업을 결심했어요.", m: "After much deliberation, my cat decided to start his own business.", kw: ["business", "startup"] },
            { p: "내 고양이는 아침 커피 없이는 하루를 시작할 수 없대요.", m: "My cat says he can't start the day without morning coffee.", kw: ["coffee", "morning"] },
        ],
    },
};
