/**
 * Le Chat Parisien — Language & Phrase Data
 * All static content data for the language learning app.
 */

// ═══════════ Supported Languages ═══════════
const LANGS = {
    french: { name: 'French', flag: '🇫🇷', native: 'Français', hi: 'Bonjour!' },
    korean: { name: 'Korean', flag: '🇰🇷', native: '한국어', hi: '안녕하세요!' },
    hebrew: { name: 'Hebrew', flag: '🇮🇱', native: 'עברית', hi: 'שלום!', rtl: true },
};

// ═══════════ Per-language Postcard Themes ═══════════
// Each language re-skins the postcard: brand title, subtitle, postmark,
// city caption, refresh button, placeholder text and motivation — all
// written natively so the whole card reads in the target language.
const THEMES = {
    french: {
        cls: 'theme-french',
        title: 'Le Chat Parisien',
        subtitle: 'Une carte postale de Paris, chaque jour',
        postmark: ['CACHET', 'DE LA POSTE', 'PARIS'],
        caption: 'Paris',
        refresh: 'Nouvelle carte postale ✉️',
        placeholder: { p: 'Cliquez pour commencer !', m: 'Click to start!' },
        motivation: 'Chaque phrase vous rapproche de la maîtrise ! 💪',
        // Native UI chrome so no foreign words leak across languages.
        ui: {
            langue: 'Langue', level: 'Niveau',
            carnet: 'Le carnet', pratique: 'En pratique', encore: 'Encore',
            grammar: 'Grammaire & vocabulaire', howTo: "Comment l'utiliser",
            spotlight: 'La phrase du jour', related: 'Autres phrases',
            comingSoon: "D'autres phrases arrivent bientôt.",
            seen: 'Phrases vues :', start: 'Commencez le français !',
        },
    },
    korean: {
        cls: 'theme-korean',
        title: '대구 고양이',
        subtitle: '매일 대구에서 온 엽서 한 장',
        postmark: ['대구', '우체국', '소인'],
        caption: '대구',
        refresh: '새 엽서 받기 ✉️',
        placeholder: { p: '눌러서 시작하세요!', m: 'Click to start!' },
        motivation: '한 문장씩, 매일 실력이 늘어요! 💪',
        ui: {
            langue: '언어', level: '수준',
            carnet: '단어장', pratique: '활용하기', encore: '더 보기',
            grammar: '문법과 어휘', howTo: '이렇게 써 보세요',
            spotlight: '오늘의 문장', related: '관련 문장',
            comingSoon: '문장을 준비하고 있어요.',
            seen: '본 문장:', start: '한국어를 시작해요!',
        },
    },
    hebrew: {
        cls: 'theme-hebrew',
        title: 'החתול הישראלי',
        subtitle: 'גלויה מישראל, בכל יום',
        postmark: ['דואר', 'ירושלים', 'ישראל'],
        caption: 'תל אביב',
        refresh: 'גלויה חדשה ✉️',
        placeholder: { p: '!לחצו כדי להתחיל', m: 'Click to start!' },
        motivation: '!כל משפט מקרב אותך לשליטה בשפה 💪',
        ui: {
            langue: 'שפה', level: 'רמה',
            carnet: 'מחברת', pratique: 'בתרגול', encore: 'עוד',
            grammar: 'דקדוק ואוצר מילים', howTo: 'איך משתמשים בזה',
            spotlight: 'משפט היום', related: 'משפטים נוספים',
            comingSoon: '.משפטים נוספים בקרוב',
            seen: ':משפטים שנראו', start: '!בואו נתחיל עברית',
        },
    },
};

// ═══════════ Fluency Levels ═══════════
const LEVELS = {
    beginner:     { name: 'Complete Beginner',  emoji: '🌱', desc: 'I know almost nothing yet' },
    elementary:   { name: 'Elementary',         emoji: '🌿', desc: 'I know basic words & greetings' },
    intermediate: { name: 'Intermediate',       emoji: '🌳', desc: 'I can hold simple conversations' },
    upper:        { name: 'Upper Intermediate', emoji: '🌲', desc: 'I can discuss many topics' },
    advanced:     { name: 'Advanced',           emoji: '🏔️', desc: 'I want to perfect my skills' },
};

// ═══════════ Quick Demo Phrases (legacy fallback) ═══════════
const DEMO = {
    french: [
        { p: "Mon chat prépare le petit-déjeuner.", m: "My cat is preparing breakfast.", kw: ["breakfast", "cook"] },
        { p: "Le chat va au travail en métro.", m: "The cat goes to work by subway.", kw: ["subway", "work"] },
        { p: "Mon chat étudie pour son examen.", m: "My cat is studying for his exam.", kw: ["study", "exam"] },
        { p: "Le chat fait les courses au supermarché.", m: "The cat goes grocery shopping at the supermarket.", kw: ["shop", "grocery"] },
        { p: "Mon chat a un rendez-vous chez le médecin.", m: "My cat has a doctor's appointment.", kw: ["doctor", "appointment"] },
        { p: "Le chat appelle ses parents tous les dimanches.", m: "The cat calls his parents every Sunday.", kw: ["call", "family"] },
        { p: "Mon chat cherche un nouvel appartement.", m: "My cat is looking for a new apartment.", kw: ["apartment", "search"] },
        { p: "Le chat prend un café avec ses collègues.", m: "The cat has coffee with his colleagues.", kw: ["coffee", "colleagues"] },
        { p: "Mon chat fait du sport le week-end.", m: "My cat exercises on weekends.", kw: ["sport", "weekend"] },
        { p: "Le chat regarde un film après le dîner.", m: "The cat watches a movie after dinner.", kw: ["movie", "dinner"] },
    ],
    korean: [
        { p: "고양이가 아침을 준비해요.", m: "The cat is preparing breakfast.", kw: ["breakfast", "cook"] },
        { p: "고양이가 지하철로 출근해요.", m: "The cat commutes to work by subway.", kw: ["subway", "work"] },
        { p: "고양이가 시험 공부를 해요.", m: "The cat is studying for an exam.", kw: ["study", "exam"] },
        { p: "고양이가 마트에서 장을 봐요.", m: "The cat goes grocery shopping at the mart.", kw: ["shop", "grocery"] },
        { p: "고양이가 병원 예약이 있어요.", m: "The cat has a hospital appointment.", kw: ["hospital", "appointment"] },
        { p: "고양이는 매주 일요일에 부모님께 전화해요.", m: "The cat calls his parents every Sunday.", kw: ["call", "family"] },
        { p: "고양이가 새 아파트를 찾고 있어요.", m: "The cat is looking for a new apartment.", kw: ["apartment", "search"] },
        { p: "고양이가 동료들과 커피를 마셔요.", m: "The cat has coffee with colleagues.", kw: ["coffee", "colleagues"] },
        { p: "고양이는 주말에 운동해요.", m: "The cat exercises on weekends.", kw: ["sport", "weekend"] },
        { p: "고양이가 저녁 식사 후에 영화를 봐요.", m: "The cat watches a movie after dinner.", kw: ["movie", "dinner"] },
    ],
};

// ═══════════ Level-Specific Phrase Banks ═══════════
const LEVEL_DEMO = {
    french: {
        beginner: [
            // A1 — Present tense, basic vocabulary, simple structures
            { p: "Mon chat est calme.", m: "My cat is calm.", kw: ["calme", "adjective"] },
            { p: "Je mange du fromage.", m: "I eat cheese.", kw: ["fromage", "food"] },
            { p: "Mon chat est paresseux.", m: "My cat is lazy.", kw: ["paresseux", "adjective"] },
            { p: "Je joue avec mes amis.", m: "I play with my friends.", kw: ["jouer", "amis"] },
            { p: "Mon chat est jeune et beau.", m: "My cat is young and handsome.", kw: ["jeune", "beau"] },
            { p: "J'aime la glace.", m: "I like ice cream.", kw: ["glace", "food"] },
            { p: "Elle est très sociable.", m: "She is very sociable.", kw: ["sociable", "adjective"] },
            { p: "Il court dans la rue.", m: "He runs in the street.", kw: ["courir", "rue"] },
            { p: "Mon chat nage dans l'eau.", m: "My cat swims in the water.", kw: ["nager", "eau"] },
            { p: "Je dors dans la chambre.", m: "I sleep in the bedroom.", kw: ["chambre", "dormir"] },
            { p: "Je travaille à la maison.", m: "I work from home.", kw: ["travailler", "maison"] },
            { p: "Il ouvre la porte.", m: "He opens the door.", kw: ["ouvrir", "porte"] },
            { p: "J'écoute de la musique.", m: "I listen to music.", kw: ["écouter", "musique"] },
            { p: "Je cherche mes amis.", m: "I'm looking for my friends.", kw: ["chercher", "amis"] },
            { p: "Mon chat est affectueux.", m: "My cat is affectionate.", kw: ["affectueux", "adjective"] },
            { p: "Les enfants grimpent sur les meubles.", m: "The kids climb on the furniture.", kw: ["grimper", "meubles"] },
            { p: "Il est un peu têtu.", m: "He is a bit stubborn.", kw: ["têtu", "adjective"] },
            { p: "J'aide mes voisins.", m: "I help my neighbors.", kw: ["aider", "voisins"] },
            { p: "J'achète un cadeau pour ma mère.", m: "I buy a gift for my mother.", kw: ["acheter", "cadeau"] },
            { p: "Je ferme la porte.", m: "I close the door.", kw: ["fermer", "porte"] },
            { p: "Je lis un livre.", m: "I read a book.", kw: ["lire", "livre"] },
            { p: "Elle écrit dans son carnet.", m: "She writes in her notebook.", kw: ["écrire", "carnet"] },
            { p: "Mon chat est aventureux.", m: "My cat is adventurous.", kw: ["aventureux", "adjective"] },
            { p: "Je prépare le dîner.", m: "I prepare dinner.", kw: ["préparer", "dîner"] },
            { p: "Il est poli avec les gens.", m: "He is polite with people.", kw: ["poli", "gens"] },
            { p: "Elle peint un beau tableau.", m: "She paints a beautiful painting.", kw: ["peindre", "beau"] },
            { p: "Je mange un plat délicieux.", m: "I eat a delicious dish.", kw: ["plat", "délicieux"] },
            { p: "Je salue mes collègues.", m: "I greet my colleagues.", kw: ["saluer", "collègues"] },
            { p: "Je suis libre le week-end.", m: "I'm free on the weekend.", kw: ["libre", "week-end"] },
            { p: "Il fait chaud, je bois de l'eau.", m: "It's hot, I drink water.", kw: ["chaud", "eau"] },
            // A1 — Conversational phrases
            { p: "De rien.", m: "You're welcome.", kw: ["polite", "welcome"] },
            { p: "Je vous en prie.", m: "You're welcome. (formal)", kw: ["formal", "polite"] },
            { p: "J'aime ça.", m: "I like that.", kw: ["aimer", "like"] },
            { p: "Ça dépend.", m: "It depends.", kw: ["depends", "maybe"] },
            { p: "Pas encore.", m: "Not yet.", kw: ["pas", "encore"] },
            { p: "Pas vraiment.", m: "Not really.", kw: ["pas", "vraiment"] },
            { p: "Bof, ça va.", m: "Meh, it's okay.", kw: ["bof", "okay"] },
            { p: "Il fait chaud.", m: "It's hot.", kw: ["chaud", "weather"] },
            { p: "Il fait froid.", m: "It's cold.", kw: ["froid", "weather"] },
            { p: "Il pleut.", m: "It's raining.", kw: ["pluie", "weather"] },
            { p: "Quelle heure est-il ?", m: "What time is it?", kw: ["heure", "time"] },
            { p: "Je dîne.", m: "I'm having dinner.", kw: ["dîner", "food"] },
            { p: "Je fais de la musculation.", m: "I do weight training.", kw: ["muscu", "sport"] },
            { p: "Je me lave le visage.", m: "I wash my face.", kw: ["visage", "routine"] },
            { p: "Tu viens d'où ?", m: "Where are you from?", kw: ["venir", "question"] },
            { p: "Je suis fatigué.", m: "I'm tired.", kw: ["fatigué", "feeling"] },
            { p: "C'est super !", m: "That's great!", kw: ["super", "expression"] },
            { p: "Où est la gare ?", m: "Where is the train station?", kw: ["gare", "direction"] },
            { p: "Je ne sais pas.", m: "I don't know.", kw: ["savoir", "negation"] },
            { p: "C'est combien ?", m: "How much is it?", kw: ["combien", "shopping"] },
            { p: "Tu as des frères et sœurs ?", m: "Do you have brothers and sisters?", kw: ["famille", "question"] },
            { p: "Je suis marié.", m: "I'm married.", kw: ["marié", "status"] },
            { p: "On se retrouve à quelle heure ?", m: "What time do we meet?", kw: ["heure", "question"] },
            { p: "Je voudrais un café, s'il vous plaît.", m: "I'd like a coffee, please.", kw: ["café", "polite"] },
            { p: "Qu'est-ce que tu fais dans la vie ?", m: "What do you do for a living?", kw: ["travail", "question"] },
            { p: "J'habite à Paris.", m: "I live in Paris.", kw: ["habiter", "city"] },
            { p: "C'est loin d'ici ?", m: "Is it far from here?", kw: ["loin", "direction"] },
            { p: "Je suis en retard.", m: "I'm late.", kw: ["retard", "time"] },
            { p: "Enchanté !", m: "Nice to meet you!", kw: ["greeting", "polite"] },
            { p: "Tu parles anglais ?", m: "Do you speak English?", kw: ["parler", "question"] },
        ],
        elementary: [
            // A2 — Passé composé, reflexive verbs, negation, questions
            { p: "Je me lève tôt le matin.", m: "I get up early in the morning.", kw: ["se lever", "tôt"] },
            { p: "Il se brosse les dents après le petit-déjeuner.", m: "He brushes his teeth after breakfast.", kw: ["se brosser", "dents"] },
            { p: "Je me douche le soir.", m: "I shower in the evening.", kw: ["se doucher", "soir"] },
            { p: "Elle s'occupe de ses enfants.", m: "She takes care of her children.", kw: ["s'occuper de", "enfants"] },
            { p: "Mon chat se couche tard.", m: "My cat goes to bed late.", kw: ["se coucher", "tard"] },
            { p: "J'ai trouvé un nouveau restaurant.", m: "I found a new restaurant.", kw: ["trouver", "restaurant"] },
            { p: "Mon chat a acheté des meubles pour sa chambre.", m: "My cat bought furniture for his bedroom.", kw: ["acheter", "meubles"] },
            { p: "J'ai rencontré mes collègues au cinéma.", m: "I met my colleagues at the cinema.", kw: ["rencontrer", "cinéma"] },
            { p: "Elle a cuisiné un plat délicieux.", m: "She cooked a delicious dish.", kw: ["cuisiner", "délicieux"] },
            { p: "On a découvert un beau magasin.", m: "We discovered a beautiful shop.", kw: ["découvrir", "magasin"] },
            { p: "Mon chat ne sort jamais sans sa laisse.", m: "My cat never goes out without his leash.", kw: ["ne...jamais", "laisse"] },
            { p: "Je n'ai rien mangé ce matin.", m: "I ate nothing this morning.", kw: ["ne...rien", "manger"] },
            { p: "Il ne veut plus dormir seul.", m: "He doesn't want to sleep alone anymore.", kw: ["ne...plus", "seul"] },
            { p: "Personne ne comprend mon chat.", m: "Nobody understands my cat.", kw: ["ne...personne", "comprendre"] },
            { p: "Je n'ai connu personne à la fête.", m: "I didn't know anyone at the party.", kw: ["personne", "passé composé"] },
            { p: "Je fais de la musculation le matin.", m: "I do weight training in the morning.", kw: ["musculation", "faire de"] },
            { p: "Il joue du piano tous les soirs.", m: "He plays piano every evening.", kw: ["jouer de", "piano"] },
            { p: "Je fais les courses à l'épicerie.", m: "I go grocery shopping at the grocery store.", kw: ["courses", "épicerie"] },
            { p: "J'ai reçu un cadeau de mes voisins.", m: "I received a gift from my neighbors.", kw: ["recevoir", "cadeau"] },
            { p: "Je sors avec mes amis deux fois par semaine.", m: "I go out with my friends twice a week.", kw: ["deux fois", "amis"] },
            { p: "Tu as l'air fatigué.", m: "You look tired.", kw: ["avoir l'air", "fatigué"] },
            { p: "Mon chat vient de manger.", m: "My cat just ate.", kw: ["venir de", "manger"] },
            { p: "Tout s'est bien passé au travail.", m: "Everything went well at work.", kw: ["tout", "bien passé"] },
            { p: "J'ai hâte de commencer ma formation.", m: "I'm looking forward to starting my training.", kw: ["avoir hâte", "formation"] },
            { p: "Je me suis présenté à mes nouveaux voisins.", m: "I introduced myself to my new neighbors.", kw: ["se présenter", "voisins"] },
            { p: "On a déménagé à la campagne.", m: "We moved to the countryside.", kw: ["déménager", "campagne"] },
            { p: "J'ai salué les invités.", m: "I greeted the guests.", kw: ["saluer", "invités"] },
            { p: "Elle s'entraîne pour une compétition de danse.", m: "She trains for a dance competition.", kw: ["s'entraîner", "danse"] },
            { p: "Mon chat a vendu sa vieille maison.", m: "My cat sold his old house.", kw: ["vendre", "vieux"] },
            { p: "J'ai commencé le bénévolat.", m: "I started volunteering.", kw: ["commencer", "bénévolat"] },
            { p: "Il a arrêté de fumer.", m: "He stopped smoking.", kw: ["arrêter", "fumer"] },
            { p: "Je continue de m'entraîner petit à petit.", m: "I continue to train little by little.", kw: ["continuer", "petit à petit"] },
            { p: "Je me suis fait beaucoup d'amis grâce à mon voisin.", m: "I made a lot of friends thanks to my neighbor.", kw: ["se faire des amis", "grâce à"] },
            { p: "Je ne me souviens pas du mot.", m: "I don't remember the word.", kw: ["se souvenir", "mot"] },
            { p: "J'ai montré ma chambre à mes amis.", m: "I showed my bedroom to my friends.", kw: ["montrer", "chambre"] },
            // A2 — Conversational phrases
            { p: "Tu as fait quoi hier ?", m: "What did you do yesterday?", kw: ["hier", "question"] },
            { p: "Tout s'est bien passé.", m: "Everything went well.", kw: ["bien", "passé"] },
            { p: "J'ai hâte !", m: "I'm looking forward to it!", kw: ["hâte", "excited"] },
            { p: "Je viens de manger.", m: "I just ate.", kw: ["venir de", "just"] },
            { p: "Il a l'air très jeune.", m: "He looks very young.", kw: ["avoir l'air", "look"] },
            { p: "Je ne me souviens pas.", m: "I don't remember.", kw: ["souvenir", "remember"] },
            { p: "Je me lève 5 minutes avant le travail.", m: "I wake up 5 minutes before work.", kw: ["se lever", "work"] },
            { p: "Je ne me lève pas tôt.", m: "I don't get up early.", kw: ["negation", "routine"] },
            { p: "Je me douche le soir.", m: "I shower at night.", kw: ["se doucher", "routine"] },
            { p: "J'écris dans un journal.", m: "I write in a diary.", kw: ["écrire", "journal"] },
            { p: "Je sors mon chat avec une laisse tous les jours.", m: "I walk my cat with a leash every day.", kw: ["laisse", "chat"] },
            { p: "Je me fais beaucoup d'amis grâce à mon chat.", m: "I make a lot of friends thanks to my cat.", kw: ["amis", "grâce à"] },
            { p: "Je donne à manger aux chats.", m: "I feed the cats.", kw: ["manger", "chat"] },
            { p: "Je brosse les poils de mon chat.", m: "I brush my cat's fur.", kw: ["poils", "chat"] },
            { p: "Tu es allée au cinéma ?", m: "Did you go to the cinema?", kw: ["cinéma", "question"] },
            { p: "Vous êtes prête ?", m: "Are you ready? (formal)", kw: ["prête", "ready"] },
            { p: "Ça vous a plu ?", m: "Did you enjoy it?", kw: ["plaire", "enjoy"] },
            { p: "Que recommandez-vous ?", m: "What do you recommend?", kw: ["recommend", "question"] },
            { p: "Combien coûte le bus ?", m: "How much does the bus cost?", kw: ["prix", "bus"] },
            { p: "À quelle heure est le prochain bus ?", m: "What time is the next bus?", kw: ["heure", "bus"] },
            { p: "Je travaille dans une entreprise technologique.", m: "I work in a tech company.", kw: ["entreprise", "work"] },
            { p: "Je ne passe pas de temps avec mes collègues.", m: "I don't spend time with my colleagues.", kw: ["collègues", "negation"] },
            { p: "Alors je me sens seule.", m: "So I feel lonely.", kw: ["seule", "feeling"] },
            { p: "Je dois partir 5 minutes plus tôt.", m: "I have to leave 5 minutes earlier.", kw: ["devoir", "tôt"] },
        ],
        intermediate: [
            // B1 — Imparfait + passé composé, depuis/il y a, COD/COI/EN/Y, comparisons, relative pronouns
            { p: "Quand j'étais jeune, je grimpais partout sur les meubles.", m: "When I was young, I used to climb everywhere on the furniture.", kw: ["imparfait", "grimper"] },
            { p: "Je marchais dans la rue quand j'ai rencontré un ami.", m: "I was walking on the street when I met a friend.", kw: ["imparfait+PC", "rencontrer"] },
            { p: "Je faisais de la musculation quand il a commencé à pleuvoir.", m: "I was doing weight training when it started raining.", kw: ["imparfait+PC", "pleuvoir"] },
            { p: "Il était paresseux, mais il a décidé de changer.", m: "He was lazy, but he decided to change.", kw: ["imparfait+PC", "décider"] },
            { p: "Je me sentais seul, alors je me suis fait des amis.", m: "I felt lonely, so I made friends.", kw: ["se sentir", "se faire des amis"] },
            { p: "Mon chat habitait en Corée quand il était jeune.", m: "My cat used to live in Korea when he was young.", kw: ["imparfait", "habiter"] },
            { p: "Je jouais du piano quand quelqu'un a frappé à la porte.", m: "I was playing piano when someone knocked on the door.", kw: ["imparfait+PC", "piano"] },
            { p: "Il réfléchissait à son avenir quand il a reçu une offre.", m: "He was thinking about his future when he received an offer.", kw: ["réfléchir", "imparfait+PC"] },
            { p: "Il faisait froid, alors je suis resté à la maison.", m: "It was cold, so I stayed home.", kw: ["imparfait+PC", "froid"] },
            { p: "Les enfants se comportaient bien devant les invités.", m: "The children were behaving well in front of the guests.", kw: ["se comporter", "imparfait"] },
            { p: "J'habite dans cette maison depuis trois ans.", m: "I've been living in this house for three years.", kw: ["depuis", "habiter"] },
            { p: "J'étudie le français depuis l'année dernière.", m: "I've been studying French since last year.", kw: ["depuis", "étudier"] },
            { p: "J'attends le bus depuis vingt minutes.", m: "I've been waiting for the bus for twenty minutes.", kw: ["depuis", "attendre"] },
            { p: "Il y a cinq ans, on a déménagé à la campagne.", m: "Five years ago, we moved to the countryside.", kw: ["il y a", "déménager"] },
            { p: "J'ai travaillé pendant douze ans dans une entreprise.", m: "I worked for twelve years in a company.", kw: ["pendant", "travailler"] },
            { p: "Ce film ? Je l'ai regardé deux fois.", m: "This movie? I watched it twice. (COD: l')", kw: ["COD", "deux fois"] },
            { p: "Des livres, j'en ai beaucoup.", m: "Books — I have a lot of them. (EN replaces des livres)", kw: ["EN", "livres"] },
            { p: "Je vais au cinéma — j'y vais avec mes amis.", m: "I go to the cinema — I go there with my friends. (Y replaces au cinéma)", kw: ["Y", "cinéma"] },
            { p: "J'ai envoyé un cadeau à ma voisine — je lui ai envoyé des fleurs.", m: "I sent a gift to my neighbor — I sent her flowers. (COI: lui)", kw: ["COI", "cadeau"] },
            { p: "Je pense à mon travail — j'y pense souvent.", m: "I think about my work — I think about it often. (Y replaces à + thing)", kw: ["Y", "penser à"] },
            { p: "Je mange de la glace tous les jours — j'en mange beaucoup.", m: "I eat ice cream every day — I eat a lot of it. (EN replaces de la glace)", kw: ["EN", "glace"] },
            { p: "Mon frère est plus aventureux que ses voisins.", m: "My brother is more adventurous than his neighbors.", kw: ["plus que", "comparatif"] },
            { p: "Ma femme est la meilleure cuisinière de la famille.", m: "My wife is the best cook in the family.", kw: ["meilleur", "superlatif"] },
            { p: "J'ai huit ans de plus que mon frère.", m: "I'm eight years older than my brother.", kw: ["de plus que", "comparatif"] },
            { p: "Le restaurant où je travaillais est fermé.", m: "The restaurant where I used to work is closed. (où = where)", kw: ["où", "pronom relatif"] },
            { p: "Le livre que je lis est sur le développement personnel.", m: "The book I'm reading is about personal development. (que = that)", kw: ["que", "pronom relatif"] },
            { p: "J'ai un ami qui est cascadeur.", m: "I have a friend who is a stunt performer. (qui = who)", kw: ["qui", "pronom relatif"] },
            { p: "Le quartier dont je parle est dangereux.", m: "The neighborhood I'm talking about is dangerous. (dont = about which)", kw: ["dont", "pronom relatif"] },
            { p: "J'ai réparé l'ordinateur de mon voisin.", m: "I fixed my neighbor's computer.", kw: ["réparer", "ordinateur"] },
            { p: "Je tapais sur l'ordinateur quand l'écran est devenu bleu.", m: "I was typing on the computer when the screen turned blue.", kw: ["imparfait+PC", "ordinateur"] },
            { p: "J'économise pour acheter de nouveaux meubles.", m: "I'm saving to buy new furniture.", kw: ["économiser", "meubles"] },
            { p: "J'évite les endroits dangereux la nuit.", m: "I avoid dangerous places at night.", kw: ["éviter", "dangereux"] },
            { p: "Je dois partir cinq minutes plus tôt pour le travail.", m: "I have to leave five minutes earlier for work.", kw: ["devoir", "plus tôt"] },
            { p: "Je me soucie de la nature et de l'environnement.", m: "I care about nature and the environment.", kw: ["se soucier de", "nature"] },
            { p: "J'ai discuté avec mes collègues pendant la pause.", m: "I chatted with my colleagues during the break.", kw: ["discuter", "collègues"] },
            { p: "J'ai décrit mon métier à mes amis.", m: "I described my job to my friends.", kw: ["décrire", "métier"] },
            { p: "Je tolère mon voisin désagréable.", m: "I tolerate my unpleasant neighbor.", kw: ["tolérer", "désagréable"] },
            { p: "On a créé une application pour trouver des amis.", m: "We created an app to find friends.", kw: ["créer", "trouver"] },
            { p: "Je viens de Corée — j'en viens et j'y retourne chaque été.", m: "I come from Korea — I come from there and return there every summer. (EN + Y)", kw: ["EN", "Y"] },
            { p: "Tu ne te lèves pas tôt ? — Si, je me lève tôt le lundi !", m: "You don't get up early? — Actually yes, I do on Monday! (si vs non)", kw: ["si", "negation"] },
            // B1 — Subjunctive
            { p: "Il faut que tu viennes à la réunion demain.", m: "You need to come to the meeting tomorrow.", kw: ["subjonctif", "réunion"] },
            { p: "Je veux que tu sois heureux.", m: "I want you to be happy.", kw: ["subjonctif", "heureux"] },
            { p: "Il est important que nous arrivions à l'heure.", m: "It's important that we arrive on time.", kw: ["subjonctif", "heure"] },
            { p: "Bien qu'il pleuve, je sors quand même.", m: "Although it's raining, I'm going out anyway.", kw: ["subjonctif", "pleuvoir"] },
            { p: "Il faut que je fasse les courses ce soir.", m: "I need to go grocery shopping tonight.", kw: ["subjonctif", "courses"] },
            { p: "Je doute qu'il vienne à la fête.", m: "I doubt he'll come to the party.", kw: ["subjonctif", "fête"] },
            { p: "Il faut que vous soyez patients.", m: "You need to be patient.", kw: ["subjonctif", "patience"] },
            { p: "Avant que tu partes, dis-moi la vérité.", m: "Before you leave, tell me the truth.", kw: ["subjonctif", "vérité"] },
            { p: "Il est nécessaire que tu apprennes le français.", m: "It's necessary that you learn French.", kw: ["subjonctif", "français"] },
            { p: "Je suis content que tu sois là.", m: "I'm glad you're here.", kw: ["subjonctif", "content"] },
            // B1 — Futur simple
            { p: "Demain, je travaillerai à la maison.", m: "Tomorrow, I will work from home.", kw: ["futur simple", "demain"] },
            { p: "L'année prochaine, nous voyagerons en France.", m: "Next year, we will travel to France.", kw: ["futur simple", "voyage"] },
            { p: "Elle finira ses études en juin.", m: "She will finish her studies in June.", kw: ["futur simple", "études"] },
            { p: "Quand je serai grand, je serai médecin.", m: "When I grow up, I will be a doctor.", kw: ["futur simple", "médecin"] },
            { p: "Tu verras, tout ira bien.", m: "You'll see, everything will be fine.", kw: ["futur simple", "bien"] },
            { p: "Nous nous marierons l'année prochaine.", m: "We will get married next year.", kw: ["futur simple", "mariage"] },
            { p: "Il pleuvra demain selon la météo.", m: "It will rain tomorrow according to the forecast.", kw: ["futur simple", "météo"] },
            { p: "Je t'appellerai dès que j'arriverai.", m: "I'll call you as soon as I arrive.", kw: ["futur simple", "appeler"] },
            { p: "Ils achèteront une nouvelle maison.", m: "They will buy a new house.", kw: ["futur simple", "maison"] },
            { p: "Qu'est-ce que tu feras après tes études ?", m: "What will you do after your studies?", kw: ["futur simple", "études"] },
            // B1 — Conditional
            { p: "Si j'avais plus de temps, je voyagerais davantage.", m: "If I had more time, I would travel more.", kw: ["conditionnel", "voyage"] },
            { p: "Si j'étais riche, j'achèterais une grande maison.", m: "If I were rich, I would buy a big house.", kw: ["conditionnel", "riche"] },
            { p: "Pourriez-vous m'aider, s'il vous plaît ?", m: "Could you help me, please?", kw: ["conditionnel", "aider"] },
            { p: "Je voudrais réserver une table pour deux.", m: "I would like to reserve a table for two.", kw: ["conditionnel", "réserver"] },
            { p: "Si tu avais le choix, où habiterais-tu ?", m: "If you had the choice, where would you live?", kw: ["conditionnel", "choix"] },
            { p: "À ta place, je ne dirais rien.", m: "In your place, I wouldn't say anything.", kw: ["conditionnel", "place"] },
            { p: "Si nous partions plus tôt, nous éviterions le trafic.", m: "If we left earlier, we would avoid the traffic.", kw: ["conditionnel", "trafic"] },
            { p: "Aimeriez-vous venir avec nous ?", m: "Would you like to come with us?", kw: ["conditionnel", "venir"] },
            { p: "Sans ton aide, je ne réussirais pas.", m: "Without your help, I wouldn't succeed.", kw: ["conditionnel", "aide"] },
            { p: "Que ferais-tu à ma place ?", m: "What would you do in my place?", kw: ["conditionnel", "place"] },
            // B1 — Imperative
            { p: "Viens ici tout de suite !", m: "Come here right now!", kw: ["impératif", "viens"] },
            { p: "Ferme la porte, s'il te plaît.", m: "Close the door, please.", kw: ["impératif", "porte"] },
            { p: "Ne sois pas en retard.", m: "Don't be late.", kw: ["impératif", "retard"] },
            { p: "Asseyez-vous, je vous prie.", m: "Please sit down. (formal)", kw: ["impératif", "asseyez"] },
            { p: "Faisons une pause.", m: "Let's take a break.", kw: ["impératif", "pause"] },
            { p: "Ne t'inquiète pas, tout va bien.", m: "Don't worry, everything's fine.", kw: ["impératif", "inquiète"] },
            { p: "Parlez plus lentement, s'il vous plaît.", m: "Please speak more slowly. (formal)", kw: ["impératif", "lentement"] },
            { p: "Allons-y !", m: "Let's go!", kw: ["impératif", "allons"] },
            { p: "Écoute-moi bien.", m: "Listen to me carefully.", kw: ["impératif", "écoute"] },
            { p: "N'oublie pas ton parapluie.", m: "Don't forget your umbrella.", kw: ["impératif", "parapluie"] },
            // B1 — Conversational phrases
            { p: "Quand j'étais enfant, je jouais du piano.", m: "When I was a child, I played the piano.", kw: ["imparfait", "piano"] },
            { p: "J'habitais en Corée.", m: "I used to live in Korea.", kw: ["imparfait", "habiter"] },
            { p: "Il faisait beau, alors j'ai fait du sport.", m: "The weather was nice, so I exercised.", kw: ["imparfait+PC", "sport"] },
            { p: "J'habite ici depuis douze ans.", m: "I've been living here for twelve years.", kw: ["depuis", "habiter"] },
            { p: "J'ai travaillé pendant 12 ans.", m: "I worked for 12 years.", kw: ["pendant", "travailler"] },
            { p: "Comment tu as découvert ce livre ?", m: "How did you discover this book?", kw: ["découvrir", "question"] },
            { p: "Tu penses que tu vas continuer de te réveiller tôt ?", m: "Do you think you'll keep waking up early?", kw: ["penser", "futur"] },
            { p: "Quelle est la chose qui est la plus importante pour toi ?", m: "What is the most important thing for you?", kw: ["important", "question"] },
            { p: "Si je dois choisir...", m: "If I have to choose...", kw: ["si", "choisir"] },
            { p: "Mon ordinateur est tombé en panne.", m: "My computer broke down.", kw: ["ordinateur", "panne"] },
            { p: "Je tapais quand soudain l'ordinateur a affiché un écran bleu.", m: "I was typing when suddenly the computer showed a blue screen.", kw: ["imparfait+PC", "ordinateur"] },
            { p: "Il faut que je répare ça vite.", m: "I need to fix this quickly.", kw: ["il faut", "réparer"] },
            { p: "Quand est-ce que je peux récupérer mon ordinateur ?", m: "When can I get my computer back?", kw: ["récupérer", "question"] },
            { p: "Pouvez-vous m'aider ?", m: "Can you help me? (formal)", kw: ["aider", "formal"] },
            { p: "J'ai beaucoup d'expérience professionnelle.", m: "I have a lot of work experience.", kw: ["expérience", "work"] },
            { p: "Vous pouvez vous présenter ?", m: "Can you introduce yourself? (formal)", kw: ["se présenter", "formal"] },
            { p: "Petit à petit.", m: "Little by little.", kw: ["petit", "progress"] },
            { p: "Tu peux répéter ?", m: "Can you repeat?", kw: ["répéter", "question"] },
            { p: "Je ne comprends pas ces mots, vous pouvez reformuler ?", m: "I don't understand these words, can you rephrase?", kw: ["comprendre", "reformuler"] },
            { p: "Vous vous offrez des cadeaux ?", m: "Do you give each other gifts?", kw: ["cadeau", "question"] },
            { p: "Tu préfères les mêmes ou différents restaurants ?", m: "Do you prefer the same or different restaurants?", kw: ["préférer", "restaurant"] },
            { p: "Comment est la semaine ? Tu fais quoi ?", m: "How's the week? What are you doing?", kw: ["semaine", "question"] },
            { p: "Tu utilises beaucoup l'IA ?", m: "Do you use AI a lot?", kw: ["AI", "question"] },
            { p: "Je suis intéressée par votre entreprise.", m: "I'm interested in your company.", kw: ["intéressé", "entreprise"] },
            { p: "J'aime les valeurs de votre entreprise.", m: "I like your company's values.", kw: ["valeurs", "entreprise"] },
            // Wedding conversation
            { p: "Beaucoup de mariages font une entrée comme ça ?", m: "Do a lot of weddings have an entrance like that?", kw: ["mariage", "question"] },
            { p: "Le marié était derrière l'écran.", m: "The groom was behind the screen.", kw: ["marié", "wedding"] },
            { p: "Combien de temps dure la cérémonie ?", m: "How long does the ceremony last?", kw: ["combien", "durée"] },
            { p: "Il y a un repas après la cérémonie ?", m: "Is there a meal after the ceremony?", kw: ["repas", "question"] },
            { p: "Habituellement, on fait un dîner après.", m: "Usually, we have a dinner afterwards.", kw: ["habituellement", "dîner"] },
            { p: "Ils portaient des vêtements traditionnels.", m: "They were wearing traditional clothes.", kw: ["vêtements", "traditionnels"] },
            { p: "J'aime l'idée d'aller dans un club après le mariage.", m: "I like the idea of going to a club after the wedding.", kw: ["idée", "mariage"] },
            { p: "Où est-ce que vous êtes allés pour la lune de miel ?", m: "Where did you go for the honeymoon?", kw: ["lune de miel", "wedding"] },
            { p: "Vous passez combien de temps en lune de miel ?", m: "How much time do you spend on your honeymoon?", kw: ["combien", "temps"] },
            { p: "La mariée était très jolie.", m: "The bride was very pretty.", kw: ["jolie", "wedding"] },
            // Family & people
            { p: "Ma belle-mère est venue nous voir.", m: "My mother-in-law came to visit us.", kw: ["belle-mère", "family"] },
            { p: "Ma grand-mère maternelle habite loin.", m: "My maternal grandmother lives far away.", kw: ["grand-mère", "family"] },
            { p: "Ils sont venus nous voir le week-end dernier.", m: "They came to see us last weekend.", kw: ["venir", "passé composé"] },
            { p: "Ma femme et moi, on aime voyager.", m: "My wife and I like to travel.", kw: ["femme", "family"] },
            { p: "Je ne pensais pas que c'était possible.", m: "I didn't think it was possible.", kw: ["penser", "imparfait"] },
            { p: "Elles ont une grande maison.", m: "They have a big house.", kw: ["avoir", "grande"] },
            { p: "Tu connais cette chanson ?", m: "Do you know this song?", kw: ["connaître", "question"] },
            // Travel & time
            { p: "Il y a très longtemps, j'habitais en France.", m: "A very long time ago, I lived in France.", kw: ["il y a", "temps"] },
            { p: "Vous êtes restés plus longtemps que prévu ?", m: "Did you stay longer than expected?", kw: ["rester", "passé composé"] },
            { p: "C'est devenu très populaire.", m: "It became very popular.", kw: ["devenir", "passé composé"] },
            { p: "Les photos sont floues, tu peux en reprendre ?", m: "The photos are blurry, can you retake them?", kw: ["floues", "photos"] },
            { p: "On voyait les étoiles depuis le balcon.", m: "We could see the stars from the balcony.", kw: ["étoiles", "imparfait"] },
            { p: "Je fais du tapis roulant tous les matins.", m: "I do the treadmill every morning.", kw: ["tapis roulant", "sport"] },
            // Animals & café conversation
            { p: "Vous pouvez toucher les animaux dans les cafés ?", m: "Can you touch the animals in the cafés?", kw: ["toucher", "question"] },
            { p: "Les hamsters ne sont pas sauvages ?", m: "Hamsters aren't wild?", kw: ["sauvage", "question"] },
            { p: "Non, ils ne sont pas domestiques.", m: "No, they're not domestic.", kw: ["domestique", "animal"] },
            { p: "Mon chat me manquait quand j'étais en voyage.", m: "I missed my cat when I was traveling.", kw: ["manquer", "imparfait"] },
            // Everyday expressions
            { p: "C'est pareil pour moi.", m: "It's the same for me.", kw: ["pareil", "expression"] },
            { p: "Il y a eu un éclair dans le ciel.", m: "There was a lightning bolt in the sky.", kw: ["éclair", "weather"] },
            { p: "Elle prie tous les soirs.", m: "She prays every evening.", kw: ["prier", "verb"] },
            { p: "Ma fille collectionne les poupées et les figurines.", m: "My daughter collects dolls and figurines.", kw: ["poupée", "figurine"] },
            // B1 — Plus-que-parfait
            { p: "J'avais déjà mangé quand il est arrivé.", m: "I had already eaten when he arrived.", kw: ["plus-que-parfait", "manger"] },
            { p: "Elle avait fini ses devoirs avant de sortir.", m: "She had finished her homework before going out.", kw: ["plus-que-parfait", "finir"] },
            { p: "Nous avions réservé une table, mais le restaurant était fermé.", m: "We had reserved a table, but the restaurant was closed.", kw: ["plus-que-parfait", "réserver"] },
            { p: "Il avait oublié son parapluie, alors il est revenu.", m: "He had forgotten his umbrella, so he came back.", kw: ["plus-que-parfait", "oublier"] },
            { p: "J'avais toujours voulu visiter le Japon.", m: "I had always wanted to visit Japan.", kw: ["plus-que-parfait", "vouloir"] },
            { p: "Ils avaient déménagé avant la fin de l'année.", m: "They had moved before the end of the year.", kw: ["plus-que-parfait", "déménager"] },
            { p: "Tu n'avais jamais goûté ce plat avant ?", m: "You had never tasted this dish before?", kw: ["plus-que-parfait", "goûter"] },
            { p: "On s'était déjà rencontrés à une fête.", m: "We had already met at a party.", kw: ["plus-que-parfait", "se rencontrer"] },
            // B1 — Passive voice
            { p: "Ce livre a été écrit par un auteur français.", m: "This book was written by a French author.", kw: ["passif", "écrire"] },
            { p: "La maison a été construite en 1920.", m: "The house was built in 1920.", kw: ["passif", "construire"] },
            { p: "Les résultats seront annoncés demain.", m: "The results will be announced tomorrow.", kw: ["passif", "annoncer"] },
            { p: "Le voleur a été arrêté par la police.", m: "The thief was arrested by the police.", kw: ["passif", "arrêter"] },
            { p: "Cette chanson est chantée partout dans le monde.", m: "This song is sung all over the world.", kw: ["passif", "chanter"] },
            { p: "Le dîner est préparé par ma grand-mère.", m: "Dinner is prepared by my grandmother.", kw: ["passif", "préparer"] },
            // B1 — Reported speech
            { p: "Il m'a dit qu'il viendrait demain.", m: "He told me he would come tomorrow.", kw: ["discours indirect", "dire"] },
            { p: "Elle a demandé si j'avais fini.", m: "She asked if I had finished.", kw: ["discours indirect", "demander"] },
            { p: "Mon patron m'a expliqué que le projet était urgent.", m: "My boss explained to me that the project was urgent.", kw: ["discours indirect", "expliquer"] },
            { p: "Il a répondu qu'il ne savait pas.", m: "He replied that he didn't know.", kw: ["discours indirect", "répondre"] },
            { p: "Elle m'a demandé ce que je voulais manger.", m: "She asked me what I wanted to eat.", kw: ["discours indirect", "ce que"] },
            { p: "Ils ont annoncé que le vol était retardé.", m: "They announced that the flight was delayed.", kw: ["discours indirect", "annoncer"] },
            // B1 — Opinions & argumentation connectors
            { p: "À mon avis, ce film est excellent.", m: "In my opinion, this movie is excellent.", kw: ["opinion", "à mon avis"] },
            { p: "Je pense que tu as raison.", m: "I think you're right.", kw: ["opinion", "penser"] },
            { p: "Je crois que c'est une bonne idée.", m: "I believe it's a good idea.", kw: ["opinion", "croire"] },
            { p: "Je suis d'accord avec toi.", m: "I agree with you.", kw: ["opinion", "d'accord"] },
            { p: "Je ne suis pas du tout d'accord.", m: "I don't agree at all.", kw: ["opinion", "désaccord"] },
            { p: "D'un côté c'est pratique, de l'autre c'est cher.", m: "On one hand it's practical, on the other it's expensive.", kw: ["argumentation", "d'un côté"] },
            { p: "Il pleut, donc je reste à la maison.", m: "It's raining, so I'm staying home.", kw: ["connecteur", "donc"] },
            { p: "Puisque tu es là, on peut commencer.", m: "Since you're here, we can start.", kw: ["connecteur", "puisque"] },
            { p: "Il est fatigué, pourtant il continue de travailler.", m: "He's tired, yet he keeps working.", kw: ["connecteur", "pourtant"] },
            { p: "J'aime le café, en revanche je déteste le thé.", m: "I like coffee; on the other hand, I hate tea.", kw: ["connecteur", "en revanche"] },
            { p: "C'est un bon restaurant, cependant les prix sont élevés.", m: "It's a good restaurant; however, the prices are high.", kw: ["connecteur", "cependant"] },
            { p: "J'adore voyager, car ça me permet de découvrir de nouvelles cultures.", m: "I love traveling because it lets me discover new cultures.", kw: ["connecteur", "car"] },
            { p: "D'abord, je fais mes devoirs, ensuite je regarde la télé, enfin je me couche.", m: "First I do my homework, then I watch TV, finally I go to bed.", kw: ["connecteur", "séquence"] },
            { p: "En ce qui me concerne, je préfère le train à l'avion.", m: "As far as I'm concerned, I prefer the train to the plane.", kw: ["opinion", "en ce qui me concerne"] },
            // B1 — More subjunctive triggers
            { p: "Je parle lentement pour que tu comprennes.", m: "I speak slowly so that you understand.", kw: ["subjonctif", "pour que"] },
            { p: "Finis tes devoirs avant qu'il soit trop tard.", m: "Finish your homework before it's too late.", kw: ["subjonctif", "avant que"] },
            { p: "On sort à moins qu'il pleuve.", m: "We'll go out unless it rains.", kw: ["subjonctif", "à moins que"] },
            { p: "J'attendrai jusqu'à ce que tu sois prêt.", m: "I'll wait until you're ready.", kw: ["subjonctif", "jusqu'à ce que"] },
            { p: "Je doute qu'il vienne ce soir.", m: "I doubt he'll come tonight.", kw: ["subjonctif", "douter que"] },
            { p: "Il est possible qu'on parte plus tôt.", m: "It's possible we leave earlier.", kw: ["subjonctif", "il est possible que"] },
            { p: "Je suis content que tu aies réussi ton examen.", m: "I'm glad you passed your exam.", kw: ["subjonctif", "content que"] },
            { p: "Il faut que nous fassions attention.", m: "We need to be careful.", kw: ["subjonctif", "il faut que"] },
            // B1 — Formal register
            { p: "Madame, Monsieur, je vous écris au sujet de ma candidature.", m: "Dear Sir/Madam, I'm writing regarding my application.", kw: ["formel", "candidature"] },
            { p: "Veuillez trouver ci-joint mon CV.", m: "Please find attached my CV.", kw: ["formel", "ci-joint"] },
            { p: "Je vous remercie par avance de votre réponse.", m: "Thank you in advance for your reply.", kw: ["formel", "remercier"] },
            { p: "Dans l'attente de votre réponse, je vous prie d'agréer mes salutations distinguées.", m: "Awaiting your reply, yours sincerely.", kw: ["formel", "salutations"] },
            { p: "Suite à notre conversation téléphonique, je vous confirme ma disponibilité.", m: "Following our phone call, I confirm my availability.", kw: ["formel", "confirmer"] },
            { p: "Je me permets de vous contacter au sujet de l'annonce.", m: "I'm taking the liberty of contacting you regarding the ad.", kw: ["formel", "se permettre"] },
            { p: "Pourriez-vous me donner plus de renseignements ?", m: "Could you give me more information?", kw: ["formel", "renseignements"] },
            { p: "Je souhaiterais prendre rendez-vous.", m: "I would like to make an appointment.", kw: ["formel", "rendez-vous"] },
            // B1 — Everyday expressions
            { p: "C'est n'importe quoi !", m: "That's nonsense!", kw: ["expression", "n'importe quoi"] },
            { p: "J'en ai marre de ce bruit.", m: "I'm fed up with this noise.", kw: ["expression", "en avoir marre"] },
            { p: "T'inquiète, c'est pas grave.", m: "Don't worry, it's no big deal.", kw: ["expression", "t'inquiète"] },
            { p: "Ça me fait plaisir de te voir.", m: "It makes me happy to see you.", kw: ["expression", "faire plaisir"] },
            { p: "On verra bien.", m: "We'll see.", kw: ["expression", "on verra"] },
            { p: "Ça vaut le coup d'essayer.", m: "It's worth trying.", kw: ["expression", "valoir le coup"] },
            { p: "Je n'en reviens pas !", m: "I can't believe it!", kw: ["expression", "revenir"] },
            { p: "Ça m'énerve.", m: "That annoys me.", kw: ["expression", "énerver"] },
            { p: "On se tient au courant.", m: "Let's keep each other posted.", kw: ["expression", "au courant"] },
            { p: "J'ai la flemme.", m: "I can't be bothered / I'm feeling lazy.", kw: ["expression", "flemme"] },
            { p: "C'est pas mon truc.", m: "It's not my thing.", kw: ["expression", "truc"] },
            { p: "Il faut que j'y aille.", m: "I have to go.", kw: ["expression", "y aller"] },
            { p: "Ça me dit rien.", m: "I don't feel like it. / Doesn't ring a bell.", kw: ["expression", "ça me dit"] },
            { p: "Tu me manques.", m: "I miss you.", kw: ["expression", "manquer"] },
            { p: "C'est la galère.", m: "It's a nightmare / hassle.", kw: ["expression", "galère"] },
            { p: "Bonne continuation !", m: "All the best! (going forward)", kw: ["expression", "continuation"] },
            { p: "Ça roule !", m: "Sounds good! / All good!", kw: ["expression", "ça roule"] },
            { p: "Je suis débordé en ce moment.", m: "I'm swamped right now.", kw: ["expression", "débordé"] },
            // B1 — Tutor session notes
            { p: "Elle est complètement folle !", m: "She's completely crazy!", kw: ["folle", "adjectif"] },
            { p: "Je suis rentrée tard hier soir.", m: "I got home late last night.", kw: ["rentrer", "passé composé"] },
            { p: "Ils n'ont plus de travail ?", m: "They don't have work anymore?", kw: ["ne...plus", "travail"] },
            { p: "J'aime accomplir mes tâches le matin.", m: "I like to get my tasks done in the morning.", kw: ["accomplir", "tâches"] },
            { p: "Faire du yoga, c'est très relaxant.", m: "Doing yoga is very relaxing.", kw: ["relaxant", "adjectif"] },
            { p: "C'est une discussion ?", m: "Is this a discussion?", kw: ["discussion", "question"] },
            { p: "En cours, on parle seulement en français.", m: "In class, we speak only in French.", kw: ["seulement", "français"] },
            { p: "Vous avez parlé de quoi ?", m: "What did you talk about?", kw: ["parler", "question"] },
            { p: "Il y avait combien de personnes ?", m: "How many people were there?", kw: ["il y avait", "imparfait"] },
            { p: "Tu te souviens pourquoi on utilise l'imparfait ?", m: "Do you remember why we use the imperfect?", kw: ["se souvenir", "imparfait"] },
            // B1 — Imparfait: describing past states, wants, and background
            { p: "J'étais fatiguée, je voulais rentrer à la maison.", m: "I was tired, I wanted to go home.", kw: ["imparfait", "vouloir"] },
            { p: "Quand j'étais enfant, je voulais devenir vétérinaire.", m: "When I was a child, I wanted to become a vet.", kw: ["imparfait", "vouloir"] },
            { p: "Je devais partir, mais il pleuvait trop fort.", m: "I had to leave, but it was raining too hard.", kw: ["imparfait", "devoir"] },
            { p: "Il faisait nuit et tout le monde dormait.", m: "It was dark and everyone was sleeping.", kw: ["imparfait", "faire"] },
            { p: "On ne savait pas quoi faire.", m: "We didn't know what to do.", kw: ["imparfait", "savoir"] },
            { p: "Je pensais que tu étais déjà parti.", m: "I thought you had already left.", kw: ["imparfait", "penser"] },
            { p: "Elle portait une belle robe rouge ce soir-là.", m: "She was wearing a beautiful red dress that evening.", kw: ["imparfait", "porter"] },
            { p: "Nous avions faim, alors on a cherché un restaurant.", m: "We were hungry, so we looked for a restaurant.", kw: ["imparfait", "avoir"] },
            { p: "Avant, je prenais toujours le bus pour aller travailler.", m: "Before, I always used to take the bus to go to work.", kw: ["imparfait", "prendre"] },
            { p: "Il y avait beaucoup de monde à la fête.", m: "There were a lot of people at the party.", kw: ["il y avait", "imparfait"] },
            // B1 — Tutor session notes (autonomie, boire)
            { p: "Ton chat est autonome.", m: "Your cat is independent.", kw: ["autonome", "adjectif"] },
            { p: "J'apprécie l'autonomie que me donne ce travail.", m: "I appreciate the independence this job gives me.", kw: ["autonomie", "travail"] },
            { p: "C'est une méthode très pratique.", m: "It's a very practical method.", kw: ["pratique", "adjectif"] },
            { p: "Le soir, nous buvons une tisane avant de dormir.", m: "In the evening, we drink a herbal tea before sleeping.", kw: ["boire", "buvons"] },
            { p: "Cette eau est parfaitement buvable.", m: "This water is perfectly drinkable.", kw: ["buvable", "adjectif"] },
            { p: "Ce café est froid, c'est imbuvable !", m: "This coffee is cold, it's undrinkable!", kw: ["imbuvable", "expression"] },
            // B1 — Imparfait: forming it from the "nous" stem (drop -ons, add -ais/-ais/-ait/-ions/-iez/-aient)
            { p: "Pour former l'imparfait, on prend le radical du « nous » et on ajoute la terminaison.", m: "To form the imperfect, you take the 'nous' stem and add the ending.", kw: ["imparfait", "radical"] },
            { p: "Avant, je voulais toujours voyager toute seule.", m: "Before, I always wanted to travel all by myself.", kw: ["imparfait", "vouloir"] },
            { p: "Chaque matin, je prenais un café avant de partir.", m: "Every morning, I used to have a coffee before leaving.", kw: ["imparfait", "prendre"] },
            { p: "Quand j'étais petite, je rangeais ma chambre tous les dimanches.", m: "When I was little, I used to tidy my room every Sunday. (ranger → rangeais, keep the e)", kw: ["imparfait", "ranger"] },
            { p: "À l'école, on finissait les cours à quatre heures.", m: "At school, we used to finish class at four o'clock.", kw: ["imparfait", "finir"] },
            { p: "Au début, je ne connaissais personne dans cette ville.", m: "At first, I didn't know anyone in this city.", kw: ["imparfait", "connaître"] },
            { p: "Autrefois, j'écrivais des lettres à ma grand-mère.", m: "In the past, I used to write letters to my grandmother.", kw: ["imparfait", "écrire"] },
            { p: "En été, nous ouvrions les fenêtres toute la nuit.", m: "In summer, we used to open the windows all night. (ouvrir → nous ouvrions)", kw: ["imparfait", "ouvrir"] },
            { p: "Le week-end, nous allions souvent à la campagne.", m: "On weekends, we often used to go to the countryside.", kw: ["imparfait", "aller"] },
            { p: "Quand j'étais enfant, je croyais au Père Noël.", m: "When I was a child, I believed in Santa Claus.", kw: ["imparfait", "croire"] },
            // B1 — Tutor session notes (wedding, BTS & past questions)
            { p: "J'ai reçu ton message ce matin.", m: "I received your message this morning.", kw: ["recevoir", "passé composé"] },
            { p: "Je dois imprimer les billets avant de partir.", m: "I have to print the tickets before leaving.", kw: ["imprimer", "verbe"] },
            { p: "Tu peux vérifier l'adresse, s'il te plaît ?", m: "Can you check the address, please?", kw: ["vérifier", "verbe"] },
            { p: "Juste le couple, ou toute la famille ?", m: "Just the couple, or the whole family?", kw: ["couple", "juste"] },
            { p: "Juste les mariés ?", m: "Just the newlyweds?", kw: ["mariés", "question"] },
            { p: "Le spectacle était vraiment divertissant.", m: "The show was really entertaining.", kw: ["divertissant", "adjectif"] },
            { p: "Avant, je ne parlais pas du tout français.", m: "Before, I didn't speak French at all.", kw: ["avant", "imparfait"] },
            { p: "J'étais entourée de ma famille et de mes amis.", m: "I was surrounded by my family and my friends.", kw: ["entouré", "adjectif"] },
            { p: "On avait perdu le contact pendant des années.", m: "We had lost touch for years.", kw: ["plus-que-parfait", "perdre"] },
            { p: "Je ne veux pas perdre de temps.", m: "I don't want to waste time.", kw: ["perdre", "verbe"] },
            { p: "Quel est ton chanteur préféré ?", m: "Who is your favorite singer?", kw: ["préféré", "adjectif"] },
            { p: "Je ne connais pas bien BTS.", m: "I don't know BTS very well.", kw: ["connaître", "négation"] },
            { p: "Tu connais les paroles de ces chansons ?", m: "Do you know the lyrics of these songs?", kw: ["chansons", "musique"] },
            { p: "J'aime beaucoup cette chanson.", m: "I really like this song.", kw: ["chanson", "musique"] },
            { p: "Quel est le titre de la chanson ?", m: "What's the title of the song?", kw: ["titre", "musique"] },
            { p: "Je travaille dans une petite entreprise.", m: "I work in a small company.", kw: ["entreprise", "travail"] },
            { p: "Tu allais à l'université ou tu travaillais ?", m: "Were you going to university or working (back then)?", kw: ["imparfait", "question"] },
            { p: "Tu avais quel âge ?", m: "How old were you?", kw: ["imparfait", "âge"] },
            { p: "Tu étais nerveuse ?", m: "Were you nervous?", kw: ["imparfait", "nerveuse"] },
            { p: "Il y avait un grand jardin derrière la maison.", m: "There was a big garden behind the house.", kw: ["il y avait", "imparfait"] },
            { p: "Il y a un problème avec ma réservation.", m: "There's a problem with my reservation.", kw: ["il y a", "présent"] },
            { p: "C'était vraiment une belle journée.", m: "It was really a beautiful day.", kw: ["c'était", "imparfait"] },
            { p: "C'était un nouveau pays pour moi.", m: "It was a new country for me.", kw: ["c'était", "pays"] },
        ],
    },
    korean: {
        beginner: [
            // 20 beginner phrases based on "Master Korean" (Chapters 1–3).
            // Formal 합쇼체 (-습니다/-ㅂ니다) register, exactly as the textbook teaches beginners.
            { p: "안녕하세요?", m: "Hello!", kw: ["greeting", "hello"] },
            { p: "저는 고양이입니다.", m: "I'm a cat.", kw: ["introduce", "be"] },
            { p: "만나서 반갑습니다.", m: "Nice to meet you.", kw: ["greeting", "polite"] },
            { p: "이것은 무엇입니까?", m: "What is this?", kw: ["what", "question"] },
            { p: "이것은 사전입니다.", m: "This is a dictionary.", kw: ["this", "noun"] },
            { p: "저 사람은 누구입니까?", m: "Who is that person?", kw: ["who", "question"] },
            { p: "저는 미국 사람이 아닙니다.", m: "I'm not American.", kw: ["negation", "nationality"] },
            { p: "고양이가 책을 읽습니다.", m: "The cat reads a book.", kw: ["read", "object"] },
            { p: "고양이가 밥을 먹습니다.", m: "The cat eats a meal.", kw: ["eat", "food"] },
            { p: "고양이가 커피를 마십니다.", m: "The cat drinks coffee.", kw: ["drink", "coffee"] },
            { p: "고양이가 음악을 듣습니다.", m: "The cat listens to music.", kw: ["listen", "music"] },
            { p: "고양이가 운동을 합니다.", m: "The cat exercises.", kw: ["exercise", "verb"] },
            { p: "고양이가 영화를 봅니다.", m: "The cat watches a movie.", kw: ["watch", "movie"] },
            { p: "지우개가 있습니까?", m: "Is there an eraser?", kw: ["exist", "question"] },
            { p: "네, 지우개가 있습니다.", m: "Yes, there is an eraser.", kw: ["exist", "yes"] },
            { p: "사전이 없습니다.", m: "There is no dictionary.", kw: ["exist", "negation"] },
            { p: "가방이 어디에 있습니까?", m: "Where is the bag?", kw: ["where", "location"] },
            { p: "가방이 책상 위에 있습니다.", m: "The bag is on the desk.", kw: ["location", "on"] },
            { p: "고양이는 도서관에 안 갑니다.", m: "The cat doesn't go to the library.", kw: ["negation", "go"] },
            { p: "학교가 크고 깨끗합니다.", m: "The school is big and clean.", kw: ["and", "adjective"] },
        ],
        elementary: [
            { p: "내 고양이는 학교에 가요.", m: "My cat goes to school.", kw: ["school", "go"] },
            { p: "고양이가 버스를 타요.", m: "The cat takes the bus.", kw: ["bus", "ride"] },
            { p: "내 고양이는 장을 봐요.", m: "My cat goes grocery shopping.", kw: ["shop", "grocery"] },
            { p: "고양이가 저녁을 준비해요.", m: "The cat prepares dinner.", kw: ["dinner", "cook"] },
        ],
        intermediate: [
            { p: "내 고양이는 올해 고등학교를 졸업해요.", m: "My cat is graduating from high school this year.", kw: ["graduate", "school"] },
            { p: "고양이가 내일 면접이 있어요.", m: "The cat has a job interview tomorrow.", kw: ["interview", "job"] },
            { p: "내 고양이가 가족을 위해 특별한 저녁을 요리했어요.", m: "My cat cooked a special dinner for the family.", kw: ["cook", "family"] },
            { p: "고양이는 매일 아침 지하철을 타고 출근해요.", m: "The cat takes the subway to work every morning.", kw: ["subway", "work"] },
        ],
        upper: [
            { p: "내 고양이는 학위를 받기까지 5년 동안 공부했어요.", m: "My cat studied for five years before getting his degree.", kw: ["degree", "study"] },
            { p: "첫 번째 면접에서 떨어졌지만 내 고양이는 포기하지 않았어요.", m: "Although he failed his first interview, my cat didn't give up.", kw: ["interview", "persist"] },
            { p: "내 고양이는 커리어를 위해 해외 이주를 고려하고 있어요.", m: "My cat is considering moving abroad for his career.", kw: ["abroad", "career"] },
            { p: "고양이는 일이 너무 많아서 휴가를 취소해야 했어요.", m: "The cat had to cancel his vacation because he had too much work.", kw: ["vacation", "cancel"] },
        ],
        advanced: [
            { p: "꾸준히 노력한 끝에 내 고양이는 꿈의 직장을 얻었어요.", m: "Through steady effort, my cat landed his dream job.", kw: ["dream", "career"] },
            { p: "내 고양이는 일과 공부를 병행하느라 눈코 뜰 새 없이 바빠요.", m: "My cat is incredibly busy juggling work and studies. (Idiom: 눈코 뜰 새 없다)", kw: ["busy", "burnout"] },
            { p: "오랫동안 고민한 끝에 내 고양이는 창업을 결심했어요.", m: "After much deliberation, my cat decided to start his own business.", kw: ["business", "startup"] },
            { p: "내 고양이는 아침 커피 없이는 하루를 시작할 수 없대요.", m: "My cat says he can't start the day without morning coffee.", kw: ["coffee", "morning"] },
        ],
    },
    hebrew: {
        beginner: [
            // Present tense, basic vocabulary — written the way Israelis write, without nikud
            { p: "החתול שלי אוכל.", m: "My cat is eating.", kw: ["eat", "food"] },
            { p: "החתול שותה חלב.", m: "The cat drinks milk.", kw: ["milk", "drink"] },
            { p: "אני אוהב את החתול שלי.", m: "I love my cat.", kw: ["love", "cat"] },
            { p: "החתול ישן על הספה.", m: "The cat sleeps on the couch.", kw: ["sleep", "couch"] },
            { p: "החתול שלי שמח.", m: "My cat is happy.", kw: ["happy", "mood"] },
            { p: "אני שותה קפה בבוקר.", m: "I drink coffee in the morning.", kw: ["coffee", "morning"] },
            { p: "החתול משחק עם כדור.", m: "The cat plays with a ball.", kw: ["play", "ball"] },
            { p: "אני הולך לעבודה.", m: "I go to work.", kw: ["work", "go"] },
            { p: "החתול שלי רעב.", m: "My cat is hungry.", kw: ["hungry", "food"] },
            { p: "שלום, מה שלומך?", m: "Hello, how are you?", kw: ["greeting", "hello"] },
            { p: "תודה רבה.", m: "Thank you very much.", kw: ["thanks", "polite"] },
            { p: "בבקשה.", m: "You're welcome. / Here you go.", kw: ["welcome", "polite"] },
            { p: "כן, בטח.", m: "Yes, sure.", kw: ["yes", "agree"] },
            { p: "אני לא יודע.", m: "I don't know.", kw: ["know", "negation"] },
            { p: "זה טעים מאוד.", m: "It's very tasty.", kw: ["tasty", "food"] },
            { p: "החתול שלי חמוד.", m: "My cat is cute.", kw: ["cute", "adjective"] },
            { p: "אני קם מוקדם בבוקר.", m: "I get up early in the morning.", kw: ["wake", "morning"] },
            { p: "החתול רץ בגינה.", m: "The cat runs in the garden.", kw: ["run", "garden"] },
            { p: "אני אוהב מוזיקה.", m: "I love music.", kw: ["music", "like"] },
            { p: "כמה זה עולה?", m: "How much does it cost?", kw: ["price", "shopping"] },
            { p: "נעים מאוד!", m: "Nice to meet you!", kw: ["greeting", "polite"] },
            { p: "אני גר בתל אביב.", m: "I live in Tel Aviv.", kw: ["live", "city"] },
            { p: "מה השעה?", m: "What time is it?", kw: ["time", "question"] },
            { p: "אני עייף.", m: "I'm tired.", kw: ["tired", "feeling"] },
        ],
        elementary: [
            // Near-future, basic connectors, simple past introduced
            { p: "מחר אני אלך לים.", m: "Tomorrow I'll go to the sea.", kw: ["sea", "future"] },
            { p: "החתול שלי אוהב לישון כל היום.", m: "My cat loves to sleep all day.", kw: ["sleep", "cat"] },
            { p: "אני רוצה לשתות מים, בבקשה.", m: "I'd like to drink water, please.", kw: ["water", "polite"] },
            { p: "אנחנו הולכים לסופר לקנות אוכל.", m: "We're going to the supermarket to buy food.", kw: ["shop", "grocery"] },
            { p: "החתול קיבל מתנה מהשכן.", m: "The cat got a gift from the neighbor.", kw: ["gift", "neighbor"] },
            { p: "אני עובד מהבית בימי שני.", m: "I work from home on Mondays.", kw: ["work", "home"] },
            { p: "בבוקר אני מצחצח שיניים ושותה קפה.", m: "In the morning I brush my teeth and drink coffee.", kw: ["routine", "morning"] },
            { p: "החתול שלי חכם אבל עצלן.", m: "My cat is smart but lazy.", kw: ["smart", "lazy"] },
            { p: "אני לומד עברית כי אני אוהב את השפה.", m: "I'm learning Hebrew because I love the language.", kw: ["learn", "language"] },
            { p: "אתה רוצה לבוא איתי?", m: "Do you want to come with me?", kw: ["come", "question"] },
            { p: "אין בעד מה.", m: "You're welcome. (in reply to thanks)", kw: ["welcome", "polite"] },
            { p: "סליחה, איפה התחנה?", m: "Excuse me, where is the station?", kw: ["direction", "station"] },
        ],
        intermediate: [
            // Past tense, subordinate clauses, conditions
            { p: "אתמול החתול שלי אכל דג טעים.", m: "Yesterday my cat ate a tasty fish.", kw: ["past", "fish"] },
            { p: "החתול שלי גר בירושלים כשהוא היה צעיר.", m: "My cat lived in Jerusalem when he was young.", kw: ["past", "city"] },
            { p: "הלכתי לשוק וקניתי ירקות טריים.", m: "I went to the market and bought fresh vegetables.", kw: ["market", "past"] },
            { p: "החתול ישן כל היום כי הוא היה עייף.", m: "The cat slept all day because he was tired.", kw: ["tired", "because"] },
            { p: "אני לומד עברית כבר שנה שלמה.", m: "I've been learning Hebrew for a whole year.", kw: ["learn", "duration"] },
            { p: "בסוף השבוע נסענו לים עם המשפחה.", m: "On the weekend we went to the sea with the family.", kw: ["weekend", "family"] },
            { p: "החתול שלי מחפש דירה חדשה.", m: "My cat is looking for a new apartment.", kw: ["apartment", "search"] },
            { p: "הכנתי ארוחת ערב מיוחדת לכל המשפחה.", m: "I made a special dinner for the whole family.", kw: ["dinner", "cook"] },
            { p: "אני חושב שאתה צודק.", m: "I think you're right.", kw: ["opinion", "agree"] },
            { p: "אם יהיה לי זמן, אבוא מחר.", m: "If I have time, I'll come tomorrow.", kw: ["condition", "future"] },
            { p: "החתול נסע באוטובוס לעבודה.", m: "The cat took the bus to work.", kw: ["bus", "work"] },
            { p: "למרות שירד גשם, יצאנו לטייל.", m: "Even though it was raining, we went for a walk.", kw: ["rain", "walk"] },
            { p: "מה עשית בסוף השבוע?", m: "What did you do over the weekend?", kw: ["weekend", "question"] },
            { p: "אני מקווה שהכול יהיה בסדר.", m: "I hope everything will be okay.", kw: ["hope", "future"] },
        ],
        upper: [
            // Complex structures, relative clauses, nuance
            { p: "החתול שעליו סיפרתי לך גר עכשיו אצל השכנים.", m: "The cat I told you about now lives with the neighbors.", kw: ["relative", "neighbor"] },
            { p: "אחרי שסיימתי את העבודה, הלכתי לפגוש חברים.", m: "After I finished work, I went to meet friends.", kw: ["after", "friends"] },
            { p: "ככל שאני לומד יותר, כך העברית נעשית קלה יותר.", m: "The more I study, the easier Hebrew becomes.", kw: ["study", "progress"] },
            { p: "היה כדאי לחכות, כי בסוף הכול הסתדר.", m: "It was worth waiting, because in the end everything worked out.", kw: ["worth", "wait"] },
            { p: "לו הייתי יודע את זה קודם, הייתי מחליט אחרת.", m: "Had I known this earlier, I would have decided differently.", kw: ["condition", "decision"] },
            { p: "החתול שלי מתלבט אם לעבור לעיר אחרת.", m: "My cat can't decide whether to move to another city.", kw: ["decide", "move"] },
            { p: "בזמן שדיברתי בטלפון, החתול ברח מהחדר.", m: "While I was talking on the phone, the cat escaped the room.", kw: ["while", "escape"] },
            { p: "זה בדיוק מה שהתכוונתי אליו.", m: "That's exactly what I meant.", kw: ["mean", "clarify"] },
        ],
        advanced: [
            // Idioms, elevated register, abstract ideas
            { p: "אחרי מחשבה ארוכה, החתול שלי החליט לפתוח עסק משלו.", m: "After long deliberation, my cat decided to open his own business.", kw: ["business", "decide"] },
            { p: "החתול שלי עסוק עד מעל לראש בין העבודה ללימודים.", m: "My cat is up to his neck between work and studies. (idiom: עד מעל הראש)", kw: ["busy", "idiom"] },
            { p: "למרות שנכשל בפעם הראשונה, החתול שלי לא ויתר.", m: "Even though he failed the first time, my cat didn't give up.", kw: ["fail", "persist"] },
            { p: "בזכות עבודה קשה ומתמדת, החתול שלי הגשים את חלומו.", m: "Through hard, persistent work, my cat realized his dream.", kw: ["dream", "effort"] },
            { p: "החתול שלי שוקל לעבור לחו\"ל בשביל הקריירה.", m: "My cat is considering moving abroad for his career.", kw: ["abroad", "career"] },
            { p: "לא היה לי מושג שזה כל כך מסובך.", m: "I had no idea it was so complicated.", kw: ["idea", "complex"] },
            { p: "נאלצתי לבטל את החופשה כי הייתה לי יותר מדי עבודה.", m: "I had to cancel the vacation because I had too much work.", kw: ["cancel", "vacation"] },
            { p: "כדאי לך לנצל את ההזדמנות הזאת.", m: "You'd do well to seize this opportunity.", kw: ["opportunity", "advice"] },
            { p: "בסופו של דבר, מה שחשוב זה לא לוותר על החלומות.", m: "At the end of the day, what matters is not giving up on your dreams.", kw: ["dream", "idiom"] },
        ],
    },
};

// ═══════════ Grammar & Vocabulary Lessons ═══════════
// Each lesson is matched against the phrase currently shown on the postcard.
// `match` is an ordered list of RegExps — the FIRST lesson whose pattern hits
// wins, so lessons are arranged from most-specific to most-general.
// `note` supports **bold**. `vocab` gives key terms; `examples` show the same
// grammar/vocab applied in other sentences (rendered in the bottom card).
const LESSONS = {
    french: [
        {
            id: 'faire-amis',
            focus: 'Se faire des amis · grâce à',
            note: "**Se faire des amis** means \u201cto make friends.\u201d **Grâce à** (thanks to) introduces the positive cause of something.",
            vocab: [
                { t: 'se faire des amis', g: 'to make friends' },
                { t: 'grâce à', g: 'thanks to' },
                { t: 'beaucoup de', g: 'a lot of' },
            ],
            match: [/grâce à/i, /me suis fait[^.]*ami/i, /me fais[^.]*ami/i, /se fait[^.]*ami/i, /fait beaucoup d['\u2019]ami/i],
            examples: [
                { p: "Je me fais des amis grâce au sport.", m: "I make friends thanks to sport." },
                { p: "Grâce à mon chat, je rencontre mes voisins.", m: "Thanks to my cat, I meet my neighbors." },
                { p: "Elle s'est fait des amis au travail.", m: "She made friends at work." },
            ],
        },
        {
            id: 'venir-de',
            focus: 'Venir de + infinitive (recent past)',
            note: "**Venir de + infinitive** expresses the recent past \u2014 something that *just* happened.",
            vocab: [
                { t: 'je viens de…', g: 'I just…' },
                { t: 'il vient de…', g: 'he just…' },
                { t: 'venir de + inf.', g: 'to have just done' },
            ],
            match: [/\b(viens|vient|venons|venez|viennent)\s+d['\u2019e]\s*[a-zàâçéèêëîïôûùüÿœ]+(er|ir|re)\b/i],
            examples: [
                { p: "Mon chat vient de se réveiller.", m: "My cat just woke up." },
                { p: "Je viens de finir mon café.", m: "I just finished my coffee." },
                { p: "Nous venons d'arriver à Paris.", m: "We just arrived in Paris." },
            ],
        },
        {
            id: 'avoir-expr',
            focus: 'Idioms with avoir',
            note: "French uses **avoir** (to have) where English uses *to be*: **avoir faim** (to be hungry), **avoir l'air** (to look/seem), **avoir hâte** (to look forward).",
            vocab: [
                { t: "avoir l'air", g: 'to look / seem' },
                { t: 'avoir hâte', g: 'to look forward' },
                { t: 'avoir faim / soif', g: 'to be hungry / thirsty' },
            ],
            match: [/\b(ai|as|a|avons|avez|ont)\s+l['\u2019]air/i, /\b(ai|as|a|avons|avez|ont)\s+hâte/i, /\b(ai|as|a|avons|avez|ont)\s+(faim|soif|peur|raison|tort|besoin|envie|sommeil)\b/i],
            examples: [
                { p: "Mon chat a l'air fatigué.", m: "My cat looks tired." },
                { p: "J'ai hâte de partir en vacances.", m: "I can't wait to go on holiday." },
                { p: "Tu as faim ? On mange ?", m: "Are you hungry? Shall we eat?" },
            ],
        },
        {
            id: 'reflexive-passe',
            focus: 'Reflexive verbs in the passé composé',
            note: "Reflexive (pronominal) verbs form the passé composé with **être**, and the past participle agrees with the subject.",
            vocab: [
                { t: 'je me suis levé(e)', g: 'I got up' },
                { t: "s'est passé", g: 'happened / went' },
                { t: 'être + participle', g: 'agrees w/ subject' },
            ],
            match: [/\b(me suis|t['\u2019]es|s['\u2019]est|se sont)\s+[a-zàâçéèêëîïôûùüÿœ]+(é|és|ée|ées)(?![a-zàâçéèêëîïôûùüÿœ])/i, /\bnous nous sommes\b/i, /\bvous vous êtes\s+[a-zàâçéèêëîïôûù]+(é|és|ée|ées)(?![a-zàâçéèêëîïôûùüÿœ])/i, /tout s['\u2019]est/i],
            examples: [
                { p: "Je me suis levé très tôt.", m: "I got up very early." },
                { p: "Elle s'est présentée aux voisins.", m: "She introduced herself to the neighbors." },
                { p: "Tout s'est bien passé.", m: "Everything went well." },
            ],
        },
        {
            id: 'passe-compose',
            focus: 'Passé composé with avoir',
            note: "The **passé composé** describes completed past actions: **avoir** (present) + past participle. Most verbs take *avoir*.",
            vocab: [
                { t: "j'ai trouvé", g: 'I found' },
                { t: 'il a acheté', g: 'he bought' },
                { t: "j'ai reçu", g: 'I received' },
            ],
            match: [/\b(ai|as|a|avons|avez|ont)\s+[a-zàâçéèêëîïôûùüÿœ]+(é|és|ée|ées|is|it|us|ue)(?![a-zàâçéèêëîïôûùüÿœ])/i, /\b(ai|as|a|avons|avez|ont)\s+(connu|reçu|vu|bu|lu|perdu|couru|voulu|pu|su|tenu|venu|répondu|entendu|attendu|vendu|rendu|descendu|découvert|ouvert|offert|souffert|pris|appris|compris|écrit|dit|eu|été|fait)(?![a-zàâçéèêëîïôûùüÿœ])/i],
            examples: [
                { p: "J'ai mangé au restaurant hier.", m: "I ate at the restaurant yesterday." },
                { p: "Mon chat a dormi toute la journée.", m: "My cat slept all day." },
                { p: "Nous avons visité le musée.", m: "We visited the museum." },
            ],
        },
        {
            id: 'conditionnel',
            focus: 'Conditional (politeness & wishes)',
            note: "The **conditional** softens requests and expresses wishes: *je voudrais* (I would like), *je pourrais* (I could).",
            vocab: [
                { t: 'je voudrais', g: 'I would like' },
                { t: 'tu pourrais', g: 'you could' },
                { t: 'ce serait', g: 'it would be' },
            ],
            match: [/\b(voudrais|voudrait|voudriez|aimerais|aimerait|pourrais|pourrait|serait|ferais|ferait|devrait|devrais)\b/i],
            examples: [
                { p: "Je voudrais un café, s'il vous plaît.", m: "I'd like a coffee, please." },
                { p: "Tu pourrais m'aider ?", m: "Could you help me?" },
                { p: "Ce serait super de se revoir.", m: "It would be great to meet again." },
            ],
        },
        {
            id: 'subjonctif',
            focus: 'Subjunctive (il faut que…)',
            note: "The **subjunctive** follows necessity, emotion, or doubt \u2014 e.g. *il faut que*, *bien que*, *pour que*.",
            vocab: [
                { t: 'il faut que', g: "it's necessary that" },
                { t: 'bien que', g: 'although' },
                { t: 'pour que', g: 'so that' },
            ],
            match: [/\bil faut que\b/i, /\bbien que\b/i, /\bpour que\b/i, /\bavant que\b/i, /\bqu['\u2019]il (soit|fasse|aille|ait|puisse|vienne)\b/i, /\bque je (sois|fasse|aille|puisse|parte)\b/i],
            examples: [
                { p: "Il faut que je parte tôt.", m: "I have to leave early." },
                { p: "Bien qu'il soit fatigué, il travaille.", m: "Although he's tired, he keeps working." },
                { p: "Je reste pour que tu puisses dormir.", m: "I'm staying so that you can sleep." },
            ],
        },
        {
            id: 'futur',
            focus: 'Simple future',
            note: "The **simple future** adds -ai, -as, -a, -ons, -ez, -ont to the infinitive. Some stems are irregular: être \u2192 *ser-*, aller \u2192 *ir-*.",
            vocab: [
                { t: 'je serai', g: 'I will be' },
                { t: 'il ira', g: 'he will go' },
                { t: 'nous mangerons', g: 'we will eat' },
            ],
            match: [/\b(serai|sera|seras|serons|serez|seront|irai|ira|iras|irons|irez|iront|aurai|aura|auras|auront|ferai|fera|feras|feront|pourrai|pourra|viendra|voudra|pleuvra)\b/i, /\b[a-zàâçéèêëîïôûùüÿœ]{2,}er(a|ai|as|ons|ez|ont)(?![a-zàâçéèêëîïôûùüÿœ])/i, /\b[a-zàâçéèêëîïôûùüÿœ]{2,}ir(a|ai|as|ons|ez|ont)(?![a-zàâçéèêëîïôûùüÿœ])/i],
            examples: [
                { p: "Demain, je travaillerai à la maison.", m: "Tomorrow I'll work from home." },
                { p: "Mon chat sera content de te voir.", m: "My cat will be happy to see you." },
                { p: "Nous irons à Paris cet été.", m: "We'll go to Paris this summer." },
            ],
        },
        {
            id: 'plus-que-parfait',
            focus: 'Pluperfect (le plus-que-parfait)',
            note: "The **plus-que-parfait** describes an action finished *before* another past action: imperfect of **avoir/être** + past participle.",
            vocab: [
                { t: "j'avais fait", g: 'I had done' },
                { t: 'il était parti', g: 'he had left' },
                { t: "s'était couché", g: 'had gone to bed' },
            ],
            match: [/\b(avais|avait|avaient|avions|aviez|étais|était|étaient|étions|étiez)\s+(?:(?:déjà|toujours|jamais|bien|enfin|encore)\s+)?[a-zàâçéèêëîïôûùüÿœ]+(é|és|ée|ées|is|it|us|ue|u|ert)(?![a-zàâçéèêëîïôûùüÿœ])/i, /\bs['\u2019]était\s+(?:(?:déjà|toujours|bien|enfin)\s+)?[a-zàâçéèêëîïôûùüÿœ]+(é|és|ée|ées|us)(?![a-zàâçéèêëîïôûùüÿœ])/i],
            examples: [
                { p: "J'avais déjà mangé quand tu es arrivé.", m: "I had already eaten when you arrived." },
                { p: "Nous avions réservé une table.", m: "We had booked a table." },
                { p: "Elle s'était couchée tôt ce soir-là.", m: "She had gone to bed early that night." },
            ],
        },
        {
            id: 'imparfait',
            focus: 'Imperfect (l\'imparfait)',
            note: "The **imparfait** paints ongoing, habitual, or background past actions (*I used to…*, *it was…*). Endings: -ais, -ait, -aient.",
            vocab: [
                { t: "j'étais", g: 'I was' },
                { t: 'il habitait', g: 'he used to live' },
                { t: 'quand j\'étais petit', g: 'when I was little' },
            ],
            match: [/\b(habitais|habitait|habitaient|grimpais|grimpait|portais|portait|portaient|voyais|voyait|voyaient|manquait|comportait|comportaient|faisais|faisait|allait|voulais|voulait|voulaient|pouvais|pouvait|devais|devait|prenais|prenait|pensais|pensait|pensaient|dormais|dormait|jouais|jouait|jouaient|regardait|mangeait|pleuvait|savais|savait|venait|disait|disaient|avait|avais|avaient|avions)\b/i, /(?:^|[\s'\u2019])(était|étais|étaient|étions|étiez)(?![a-zàâçéèêëîïôûùüÿœ])/i],
            examples: [
                { p: "Quand j'étais petit, j'habitais à Paris.", m: "When I was little, I lived in Paris." },
                { p: "Mon chat jouait dans le jardin.", m: "My cat used to play in the garden." },
                { p: "Il faisait beau ce jour-là.", m: "The weather was nice that day." },
            ],
        },
        {
            id: 'imperatif',
            focus: 'Imperative (giving orders & invitations)',
            note: "The **imperative** gives orders, advice, or invitations \u2014 drop the subject. The *tu* form of -er verbs loses its final -s. **Veuillez** is the polite formal command.",
            vocab: [
                { t: 'écoute / écoutez', g: 'listen!' },
                { t: 'allons-y', g: "let's go" },
                { t: 'veuillez…', g: 'please (formal)' },
            ],
            match: [/^(viens|venez|va|allez|allons|fais|faisons|faites|écoute|écoutez|parle|parlez|regarde|regardez|prends|prenez|donne|donnez|arrête|arrêtez|attends|attendez|dis|dites|reste|restez|entre|entrez)\b/i, /\b(allons-y|écoute-moi|écoutez-moi|assieds-toi|asseyez-vous|tais-toi|taisez-vous|dépêche-toi|dépêchez-vous|vas-y)\b/i, /\bveuillez\b/i],
            examples: [
                { p: "Viens ici tout de suite !", m: "Come here right now!" },
                { p: "Asseyez-vous, je vous en prie.", m: "Please have a seat." },
                { p: "Parlez plus lentement, s'il vous plaît.", m: "Please speak more slowly." },
            ],
        },
        {
            id: 'reflexive',
            focus: 'Reflexive (pronominal) verbs',
            note: "**Reflexive verbs** use a pronoun (me, te, se, nous, vous) when the subject acts on itself \u2014 daily-routine verbs are often reflexive.",
            vocab: [
                { t: 'se lever', g: 'to get up' },
                { t: 'se coucher', g: 'to go to bed' },
                { t: 'se laver', g: 'to wash (oneself)' },
            ],
            match: [/\b(je me|tu te|il se|elle se|on se|nous nous|vous vous)\s+[a-zàâçéèêëîïôûù]/i, /\bchat se\s+[a-zàâçéèêëîïôûù]/i, /\bse (lève|lever|couche|coucher|brosse|brosser|douche|doucher|lave|laver|occupe|occuper|entraîne|entraîner|présente|présenter|souvient|souvenir|sent|sentir|repose|reposer)\b/i, /\b[mts]['\u2019](occupe|entraîne|appelle|habille|réveille|amuse|ennuie|installe|arrête|inquiète|repose|prépare|dépêche)/i],
            examples: [
                { p: "Je me lève à sept heures.", m: "I get up at seven." },
                { p: "Mon chat se lave après le repas.", m: "My cat washes himself after the meal." },
                { p: "Nous nous couchons tard le week-end.", m: "We go to bed late on weekends." },
            ],
        },
        {
            id: 'negation',
            focus: 'Negation (ne … pas / jamais / rien)',
            note: "Negation wraps the verb: **ne … pas**. Swap *pas* for **jamais** (never), **rien** (nothing), **plus** (no longer), **personne** (nobody).",
            vocab: [
                { t: 'ne… pas', g: 'not' },
                { t: 'ne… jamais', g: 'never' },
                { t: 'ne… plus', g: 'no longer' },
            ],
            match: [/\bne\s+[a-zàâçéèêëîïôûù'\u2019]+\s+(pas|jamais|rien|plus|personne|que)\b/i, /\bn['\u2019][a-zàâçéèêëîïôûù]+\s+(pas|jamais|rien|plus|personne)\b/i, /\bpersonne ne\b/i, /\bne (sais|veux|peux|sort|dors) (pas|plus|jamais)\b/i],
            examples: [
                { p: "Je ne sais pas encore.", m: "I don't know yet." },
                { p: "Mon chat ne dort jamais la nuit.", m: "My cat never sleeps at night." },
                { p: "Il n'y a plus de lait.", m: "There's no more milk." },
            ],
        },
        {
            id: 'faire-jouer-de',
            focus: 'Faire de · Jouer de',
            note: "Use **faire du/de la** for sports & activities, and **jouer du/de la** for musical instruments.",
            vocab: [
                { t: 'faire de la muscu', g: 'to work out' },
                { t: 'jouer du piano', g: 'to play piano' },
                { t: 'faire les courses', g: 'to go shopping' },
            ],
            match: [/\b(fais|fait|faisons|faites|font)\s+(du|de la|de l['\u2019])/i, /\b(joue|joues|jouons|jouez|jouent)\s+(du|de la|de l['\u2019])/i, /faire de la|faire les courses/i],
            examples: [
                { p: "Je fais du sport le matin.", m: "I do sport in the morning." },
                { p: "Elle joue de la guitare.", m: "She plays the guitar." },
                { p: "On fait de la randonnée le dimanche.", m: "We go hiking on Sundays." },
            ],
        },
        {
            id: 'devoir',
            focus: 'Devoir + infinitive (obligation)',
            note: "**Devoir + infinitive** expresses obligation or necessity \u2014 *must / have to*.",
            vocab: [
                { t: 'je dois', g: 'I must / have to' },
                { t: 'on doit', g: 'one must' },
                { t: 'devoir + inf.', g: 'to have to do' },
            ],
            match: [/\b(dois|doit|devons|devez|doivent)\s+[a-zàâçéèêëîïôûùüÿœ]+(er|ir|re)\b/i],
            examples: [
                { p: "Je dois partir maintenant.", m: "I must leave now." },
                { p: "Mon chat doit voir le vétérinaire.", m: "My cat has to see the vet." },
                { p: "Nous devons réserver une table.", m: "We have to book a table." },
            ],
        },
        {
            id: 'weather',
            focus: 'Talking about the weather',
            note: "Weather uses the impersonal **il fait +** adjective, or a single verb: **il pleut** (it's raining), **il neige** (it's snowing).",
            vocab: [
                { t: 'il fait chaud', g: "it's hot" },
                { t: 'il fait froid', g: "it's cold" },
                { t: 'il pleut', g: "it's raining" },
            ],
            match: [/\bil fait (chaud|froid|beau|mauvais|frais|bon|gris)\b/i, /\bil pleut\b/i, /\bil neige\b/i],
            examples: [
                { p: "Il fait beau aujourd'hui.", m: "The weather is nice today." },
                { p: "Il pleut, je reste à la maison.", m: "It's raining, I'm staying home." },
                { p: "En hiver, il fait très froid.", m: "In winter, it's very cold." },
            ],
        },
        {
            id: 'partitive',
            focus: 'Partitive articles (du, de la, de l\u2019)',
            note: "The **partitive** (du, de la, de l') means *some / an unspecified amount* \u2014 used with food, drink, and abstract nouns.",
            vocab: [
                { t: 'du (m.)', g: 'some' },
                { t: 'de la (f.)', g: 'some' },
                { t: "de l' (vowel)", g: 'some' },
            ],
            match: [/\b(du|de la|de l['\u2019])\s+[a-zàâçéèêëîïôûùüÿœ]/i],
            examples: [
                { p: "Je bois du café le matin.", m: "I drink coffee in the morning." },
                { p: "Il mange de la soupe.", m: "He eats soup." },
                { p: "Tu veux de l'eau ?", m: "Do you want some water?" },
            ],
        },
        {
            id: 'question',
            focus: 'Asking questions',
            note: "Three ways to ask: rising intonation (*Tu viens ?*), **est-ce que** (*Est-ce que tu viens ?*), or inversion (*Viens-tu ?*).",
            vocab: [
                { t: 'est-ce que…?', g: '(question marker)' },
                { t: "qu'est-ce que…?", g: 'what…?' },
                { t: 'combien ?', g: 'how much / many?' },
            ],
            match: [/\?\s*$/],
            examples: [
                { p: "Est-ce que tu aimes les chats ?", m: "Do you like cats?" },
                { p: "Qu'est-ce que tu fais ce soir ?", m: "What are you doing tonight?" },
                { p: "Combien ça coûte ?", m: "How much does it cost?" },
            ],
        },
        {
            id: 'etre-adj',
            focus: 'Être + adjective (describing)',
            note: "Use **être** (to be) + adjective to describe. The adjective agrees in gender and number with the subject.",
            vocab: [
                { t: 'il est / elle est', g: 'he is / she is' },
                { t: 'ils / elles sont', g: 'they are' },
                { t: 'agreement', g: '-e (f.), -s (pl.)' },
            ],
            match: [/\b(suis|es|est|sommes|êtes|sont)\b/i],
            examples: [
                { p: "Mon chat est très calme.", m: "My cat is very calm." },
                { p: "Elle est sociable et gentille.", m: "She is sociable and kind." },
                { p: "Ils sont fatigués ce soir.", m: "They are tired tonight." },
            ],
        },
        {
            id: 'present-er',
            focus: 'Present tense: -er verbs',
            note: "Regular **-er verbs** are the biggest French group. Drop **-er** and add: -e, -es, -e, -ons, -ez, -ent.",
            vocab: [
                { t: 'je mange', g: 'I eat' },
                { t: 'tu manges', g: 'you eat' },
                { t: 'nous mangeons', g: 'we eat' },
            ],
            match: [/\bje\s+[a-zàâçéèêëîïôûùüÿœ]+e\b/i, /\b(mange|joue|travaille|écoute|cherche|aide|achète|ferme|prépare|salue|habite|parle|aime|donne|brosse|regarde|adore|déteste|cuisine)\b/i],
            examples: [
                { p: "Je travaille à la maison.", m: "I work from home." },
                { p: "Nous écoutons de la musique.", m: "We listen to music." },
                { p: "Mon chat mange à midi.", m: "My cat eats at noon." },
            ],
        },
    ],
};
